import type { UniversityApplicationProfile } from "@/lib/site-data";

type BulkAdmissionSeed = {
  name: string;
  website: string;
  sourceUrl: string;
  location: string;
  focus: string;
  majors: string[];
};

type BulkEnrichment = {
  website: string;
  summary: string;
  majors: string[];
  applicationProfile: UniversityApplicationProfile;
};

const slugifyBulkName = (name: string) =>
  name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const seeds: BulkAdmissionSeed[] = [
  { name: "Anhui Agricultural University", website: "https://www.ahau.edu.cn/", sourceUrl: "https://gjy.ahau.edu.cn/", location: "Hefei", focus: "agriculture, forestry, food science, life sciences, engineering, and business", majors: ["Agriculture", "Engineering", "Business", "Chinese Language"] },
  { name: "Anhui Medical University", website: "https://www.ahmu.edu.cn/", sourceUrl: "https://international.ahmu.edu.cn/", location: "Hefei", focus: "clinical medicine, pharmacy, public health, nursing, and medical sciences", majors: ["Medicine", "Pharmacy", "Public Health", "Chinese Language"] },
  { name: "Anhui Normal University", website: "https://www.ahnu.edu.cn/", sourceUrl: "https://english.ahnu.edu.cn/", location: "Wuhu", focus: "teacher education, Chinese language, humanities, sciences, and arts", majors: ["Education", "Chinese Language", "Business", "Computer Science"] },
  { name: "Anhui University", website: "https://www.ahu.edu.cn/", sourceUrl: "https://sie.ahu.edu.cn/", location: "Hefei", focus: "liberal arts, law, business, computer science, electronics, and materials", majors: ["Computer Science", "Business", "Chinese Language", "Engineering"] },
  { name: "Beihua University", website: "https://www.beihua.edu.cn/", sourceUrl: "https://gjjy.beihua.edu.cn/", location: "Jilin", focus: "medicine, engineering, education, forestry, Chinese language, and business", majors: ["Medicine", "Engineering", "Chinese Language", "Education"] },
  { name: "Beijing Forestry University", website: "https://english.bjfu.edu.cn/", sourceUrl: "https://iso.bjfu.edu.cn/", location: "Beijing", focus: "forestry, ecology, landscape architecture, environmental science, biology, and design", majors: ["Forestry", "Ecology", "Architecture", "Engineering"] },
  { name: "Beijing International Studies University", website: "https://www.bisu.edu.cn/", sourceUrl: "https://admission.bisu.edu.cn/", location: "Beijing", focus: "foreign languages, tourism management, international business, translation, and China studies", majors: ["Chinese Language", "Business", "Tourism", "Translation"] },
  { name: "Beijing Sport University", website: "https://www.bsu.edu.cn/", sourceUrl: "https://sie.bsu.edu.cn/", location: "Beijing", focus: "sport science, coaching, physical education, rehabilitation, and Chinese language", majors: ["Sports Science", "Education", "Chinese Language", "Medicine"] },
  { name: "Beijing Technology and Business University", website: "https://www.btbu.edu.cn/", sourceUrl: "https://sie.btbu.edu.cn/", location: "Beijing", focus: "business, economics, food science, light industry, finance, and management", majors: ["Business", "Finance", "Food Science", "Engineering"] },
  { name: "Beijing University of Chemical Technology", website: "https://english.buct.edu.cn/", sourceUrl: "https://international.buct.edu.cn/", location: "Beijing", focus: "chemical engineering, materials, biotechnology, environmental engineering, and business", majors: ["Chemical Engineering", "Materials Science", "Engineering", "Business"] },
  { name: "Beijing University of Technology", website: "https://english.bjut.edu.cn/", sourceUrl: "https://isc.bjut.edu.cn/", location: "Beijing", focus: "engineering, computer science, materials, architecture, environmental science, and business", majors: ["Engineering", "Computer Science", "Architecture", "Business"] },
  { name: "Bohai University", website: "https://www.bhu.edu.cn/", sourceUrl: "https://gjjyxy.bhu.edu.cn/", location: "Jinzhou", focus: "education, food science, Chinese language, business, engineering, and humanities", majors: ["Education", "Food Science", "Chinese Language", "Business"] },
  { name: "Capital Medical University", website: "https://www.ccmu.edu.cn/", sourceUrl: "https://siec.ccmu.edu.cn/", location: "Beijing", focus: "clinical medicine, stomatology, public health, nursing, and biomedical sciences", majors: ["Medicine", "Dentistry", "Public Health", "Nursing"] },
  { name: "Capital Normal University", website: "https://www.cnu.edu.cn/", sourceUrl: "https://cie.cnu.edu.cn/", location: "Beijing", focus: "education, Chinese language, humanities, sciences, music, arts, and teacher training", majors: ["Education", "Chinese Language", "Arts", "Computer Science"] },
  { name: "Capital University of Economics and Business", website: "https://www.cueb.edu.cn/", sourceUrl: "https://ie.cueb.edu.cn/", location: "Beijing", focus: "economics, finance, accounting, business, statistics, and public administration", majors: ["Business", "Finance", "Economics", "Accounting"] },
  { name: "Central China Normal University", website: "https://english.ccnu.edu.cn/", sourceUrl: "https://iso.ccnu.edu.cn/", location: "Wuhan", focus: "education, psychology, Chinese language, humanities, sciences, and information technology", majors: ["Education", "Psychology", "Chinese Language", "Computer Science"] },
  { name: "Chang'an University", website: "https://en.chd.edu.cn/", sourceUrl: "https://ies.chd.edu.cn/", location: "Xi'an", focus: "transportation, civil engineering, geosciences, vehicles, architecture, and logistics", majors: ["Engineering", "Civil Engineering", "Transport", "Architecture"] },
  { name: "Changchun University", website: "https://www.ccu.edu.cn/", sourceUrl: "https://gjy.ccu.edu.cn/", location: "Changchun", focus: "engineering, business, special education, Chinese language, design, and applied sciences", majors: ["Engineering", "Business", "Education", "Chinese Language"] },
  { name: "Changchun University of Chinese Medicine", website: "https://www.ccucm.edu.cn/", sourceUrl: "https://iec.ccucm.edu.cn/", location: "Changchun", focus: "traditional Chinese medicine, acupuncture, rehabilitation, pharmacy, and nursing", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Changchun University of Science and Technology", website: "https://www.cust.edu.cn/", sourceUrl: "https://ie.cust.edu.cn/", location: "Changchun", focus: "optics, electronics, computer science, mechanical engineering, materials, and business", majors: ["Engineering", "Computer Science", "Electronics", "Business"] },
  { name: "Changsha University of Science and Technology", website: "https://www.csust.edu.cn/", sourceUrl: "https://www.csust.edu.cn/gjjl/", location: "Changsha", focus: "civil engineering, transport, electrical engineering, water resources, computer science, and business", majors: ["Engineering", "Civil Engineering", "Computer Science", "Business"] },
  { name: "Chengdu University of Traditional Chinese Medicine", website: "https://www.cdutcm.edu.cn/", sourceUrl: "https://iec.cdutcm.edu.cn/", location: "Chengdu", focus: "traditional Chinese medicine, acupuncture, pharmacy, nursing, and rehabilitation", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "China Academy of Art", website: "https://www.caa.edu.cn/", sourceUrl: "https://admission.caa.edu.cn/", location: "Hangzhou", focus: "fine arts, design, media art, architecture, art history, and Chinese culture", majors: ["Arts", "Design", "Architecture", "Chinese Language"] },
  { name: "China Three Gorges University", website: "https://www.ctgu.edu.cn/", sourceUrl: "https://sis.ctgu.edu.cn/", location: "Yichang", focus: "hydropower, civil engineering, medicine, electrical engineering, management, and Chinese language", majors: ["Engineering", "Medicine", "Civil Engineering", "Business"] },
  { name: "China University of Geosciences Beijing", website: "https://en.cugb.edu.cn/", sourceUrl: "https://sie.cugb.edu.cn/", location: "Beijing", focus: "geosciences, resources, environmental science, jewelry, engineering, and computer science", majors: ["Geosciences", "Engineering", "Environmental Science", "Computer Science"] },
  { name: "China University of Geosciences Wuhan", website: "https://en.cug.edu.cn/", sourceUrl: "https://iec.cug.edu.cn/", location: "Wuhan", focus: "earth sciences, resources, environmental science, engineering, computer science, and management", majors: ["Geosciences", "Engineering", "Environmental Science", "Computer Science"] },
  { name: "China University of Mining and Technology", website: "https://en.cumt.edu.cn/", sourceUrl: "https://sie.cumt.edu.cn/", location: "Xuzhou", focus: "mining, safety engineering, energy, civil engineering, computer science, and management", majors: ["Engineering", "Mining Engineering", "Computer Science", "Business"] },
  { name: "China University of Petroleum Huadong", website: "https://english.upc.edu.cn/", sourceUrl: "https://cie.upc.edu.cn/", location: "Qingdao", focus: "petroleum engineering, chemical engineering, geosciences, computer science, energy, and business", majors: ["Petroleum Engineering", "Chemical Engineering", "Computer Science", "Business"] },
  { name: "China University of Political Science and Law", website: "https://en.cupl.edu.cn/", sourceUrl: "https://gjy.cupl.edu.cn/", location: "Beijing", focus: "law, political science, international relations, business law, Chinese law, and Chinese language", majors: ["Law", "International Relations", "Business", "Chinese Language"] },
  { name: "Chongqing Jiaotong University", website: "https://www.cqjtu.edu.cn/", sourceUrl: "https://international.cqjtu.edu.cn/", location: "Chongqing", focus: "transportation, civil engineering, water resources, logistics, engineering, and management", majors: ["Transport", "Civil Engineering", "Engineering", "Business"] },
  { name: "Chongqing Medical University", website: "https://english.cqmu.edu.cn/", sourceUrl: "https://international.cqmu.edu.cn/", location: "Chongqing", focus: "clinical medicine, pediatrics, public health, pharmacy, nursing, and biomedical sciences", majors: ["Medicine", "Pediatrics", "Pharmacy", "Nursing"] },
  { name: "Chongqing University of Posts and Telecommunications", website: "https://english.cqupt.edu.cn/", sourceUrl: "https://international.cqupt.edu.cn/", location: "Chongqing", focus: "communications, computer science, software, automation, electronics, and digital media", majors: ["Computer Science", "Telecommunications", "Engineering", "Artificial Intelligence"] },
  { name: "Communication University of China", website: "https://en.cuc.edu.cn/", sourceUrl: "https://iso.cuc.edu.cn/", location: "Beijing", focus: "journalism, communication, film, television, digital media, animation, and Chinese language", majors: ["Communication", "Film", "Digital Media", "Chinese Language"] },
  { name: "Dalian Jiaotong University", website: "https://www.djtu.edu.cn/", sourceUrl: "https://sie.djtu.edu.cn/", location: "Dalian", focus: "rail transit, mechanical engineering, transport, materials, automation, and computer science", majors: ["Engineering", "Transport", "Mechanical Engineering", "Computer Science"] },
  { name: "Dalian Medical University", website: "https://www.dmu.edu.cn/", sourceUrl: "https://international.dmu.edu.cn/", location: "Dalian", focus: "clinical medicine, stomatology, pharmacy, nursing, and public health", majors: ["Medicine", "Dentistry", "Pharmacy", "Nursing"] },
  { name: "Dalian Polytechnic University", website: "https://www.dlpu.edu.cn/", sourceUrl: "https://gjjl.dlpu.edu.cn/", location: "Dalian", focus: "food science, light industry, textiles, design, engineering, and business", majors: ["Food Science", "Engineering", "Design", "Business"] },
  { name: "Dalian University of Foreign Languages", website: "https://www.dlufl.edu.cn/", sourceUrl: "https://sie.dlufl.edu.cn/", location: "Dalian", focus: "languages, translation, Chinese language, business, tourism, and international communication", majors: ["Chinese Language", "Translation", "Business", "Tourism"] },
  { name: "East China University of Political Science and Law", website: "https://www.ecupl.edu.cn/", sourceUrl: "https://ies.ecupl.edu.cn/", location: "Shanghai", focus: "law, international law, business law, political science, public administration, and Chinese language", majors: ["Law", "International Relations", "Business", "Chinese Language"] },
  { name: "East China University of Science and Technology", website: "https://english.ecust.edu.cn/", sourceUrl: "https://ies.ecust.edu.cn/", location: "Shanghai", focus: "chemical engineering, materials, biotechnology, pharmacy, environmental science, and business", majors: ["Chemical Engineering", "Materials Science", "Pharmacy", "Business"] },
  { name: "Fujian Agriculture and Forestry University", website: "https://www.fafu.edu.cn/", sourceUrl: "https://english.fafu.edu.cn/", location: "Fuzhou", focus: "agriculture, forestry, food science, ecology, life sciences, and business", majors: ["Agriculture", "Forestry", "Food Science", "Business"] },
  { name: "Fujian Medical University", website: "https://www.fjmu.edu.cn/", sourceUrl: "https://oec.fjmu.edu.cn/", location: "Fuzhou", focus: "clinical medicine, public health, pharmacy, nursing, and medical technology", majors: ["Medicine", "Public Health", "Pharmacy", "Nursing"] },
  { name: "Fujian Normal University", website: "https://www.fjnu.edu.cn/", sourceUrl: "https://iccs.fjnu.edu.cn/", location: "Fuzhou", focus: "education, Chinese language, humanities, sciences, arts, and business", majors: ["Education", "Chinese Language", "Business", "Computer Science"] },
  { name: "Fuzhou University", website: "https://www.fzu.edu.cn/", sourceUrl: "https://oec.fzu.edu.cn/", location: "Fuzhou", focus: "engineering, computer science, chemistry, architecture, economics, and business", majors: ["Engineering", "Computer Science", "Chemistry", "Business"] },
  { name: "Guangdong University of Foreign Studies", website: "https://www.gdufs.edu.cn/", sourceUrl: "https://iie-en.gdufs.edu.cn/", location: "Guangzhou", focus: "languages, international business, translation, law, journalism, and Chinese language", majors: ["Chinese Language", "Business", "Translation", "Law"] },
  { name: "Guangxi Medical University", website: "https://www.gxmu.edu.cn/", sourceUrl: "https://gjjyxy.gxmu.edu.cn/", location: "Nanning", focus: "clinical medicine, public health, pharmacy, nursing, and tropical medicine", majors: ["Medicine", "Public Health", "Pharmacy", "Nursing"] },
  { name: "Guangxi Normal University", website: "https://www.gxnu.edu.cn/", sourceUrl: "https://www.gxnu.edu.cn/gjjy/", location: "Guilin", focus: "education, Chinese language, humanities, tourism, sciences, and arts", majors: ["Education", "Chinese Language", "Tourism", "Business"] },
  { name: "Guangxi University", website: "https://www.gxu.edu.cn/", sourceUrl: "https://gjy.gxu.edu.cn/", location: "Nanning", focus: "engineering, agriculture, business, computer science, civil engineering, and Chinese language", majors: ["Engineering", "Agriculture", "Computer Science", "Business"] },
  { name: "Guangzhou Medical University", website: "https://www.gzhmu.edu.cn/", sourceUrl: "https://international.gzhmu.edu.cn/", location: "Guangzhou", focus: "clinical medicine, respiratory medicine, public health, nursing, and biomedical sciences", majors: ["Medicine", "Public Health", "Nursing", "Pharmacy"] },
  { name: "Guangzhou University of Chinese Medicine", website: "https://www.gzucm.edu.cn/", sourceUrl: "https://iec.gzucm.edu.cn/", location: "Guangzhou", focus: "traditional Chinese medicine, acupuncture, rehabilitation, pharmacy, and nursing", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Guilin University of Electronic Technology", website: "https://www.guet.edu.cn/", sourceUrl: "https://gj.guet.edu.cn/", location: "Guilin", focus: "electronics, communications, computer science, automation, mechanical engineering, and business", majors: ["Electronics", "Computer Science", "Engineering", "Business"] },
  { name: "Guizhou University", website: "https://www.gzu.edu.cn/", sourceUrl: "https://oiec.gzu.edu.cn/", location: "Guiyang", focus: "engineering, agriculture, computer science, business, ecology, and Chinese language", majors: ["Engineering", "Agriculture", "Computer Science", "Business"] },
  { name: "Hainan University", website: "https://en.hainanu.edu.cn/", sourceUrl: "https://ha.hainanu.edu.cn/haoso/", location: "Haikou", focus: "tourism, tropical agriculture, marine science, law, business, and Chinese language", majors: ["Tourism", "Agriculture", "Marine Science", "Business"] },
  { name: "Hangzhou Normal University", website: "https://www.hznu.edu.cn/", sourceUrl: "https://ic.hznu.edu.cn/", location: "Hangzhou", focus: "education, Chinese language, humanities, medicine, sciences, and business", majors: ["Education", "Chinese Language", "Medicine", "Business"] },
  { name: "Harbin Medical University", website: "https://www.hrbmu.edu.cn/", sourceUrl: "https://iec.hrbmu.edu.cn/", location: "Harbin", focus: "clinical medicine, public health, pharmacy, nursing, and medical research", majors: ["Medicine", "Public Health", "Pharmacy", "Nursing"] },
  { name: "Harbin Normal University", website: "https://www.hrbnu.edu.cn/", sourceUrl: "https://gjjyxy.hrbnu.edu.cn/", location: "Harbin", focus: "teacher education, Chinese language, arts, humanities, sciences, and business", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Harbin University of Science and Technology", website: "https://www.hrbust.edu.cn/", sourceUrl: "https://gjjy.hrbust.edu.cn/", location: "Harbin", focus: "electrical engineering, mechanical engineering, computer science, materials, and business", majors: ["Engineering", "Electrical Engineering", "Computer Science", "Business"] },
  { name: "Hebei Medical University", website: "https://www.hebmu.edu.cn/", sourceUrl: "https://iec.hebmu.edu.cn/", location: "Shijiazhuang", focus: "clinical medicine, pharmacy, nursing, public health, and traditional Chinese medicine", majors: ["Medicine", "Pharmacy", "Nursing", "Public Health"] },
  { name: "Hebei Normal University", website: "https://www.hebtu.edu.cn/", sourceUrl: "https://gjxy.hebtu.edu.cn/", location: "Shijiazhuang", focus: "education, Chinese language, humanities, sciences, arts, and business", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Hebei University", website: "https://www.hbu.edu.cn/", sourceUrl: "https://ciee.hbu.edu.cn/", location: "Baoding", focus: "humanities, law, business, computer science, medicine, and Chinese language", majors: ["Chinese Language", "Business", "Computer Science", "Law"] },
  { name: "Hebei University of Economics and Business", website: "https://www.heuet.edu.cn/", sourceUrl: "https://gjjy.heuet.edu.cn/", location: "Shijiazhuang", focus: "economics, finance, accounting, business, law, and management", majors: ["Business", "Finance", "Economics", "Accounting"] },
  { name: "Hebei University of Technology", website: "https://www.hebut.edu.cn/", sourceUrl: "https://sie.hebut.edu.cn/", location: "Tianjin", focus: "engineering, materials, electrical engineering, computer science, architecture, and business", majors: ["Engineering", "Electrical Engineering", "Computer Science", "Business"] },
  { name: "Hefei University of Technology", website: "https://en.hfut.edu.cn/", sourceUrl: "https://gjjy.hfut.edu.cn/", location: "Hefei", focus: "mechanical engineering, vehicle engineering, computer science, management, materials, and architecture", majors: ["Engineering", "Computer Science", "Vehicle Engineering", "Business"] },
  { name: "Heilongjiang University", website: "https://www.hlju.edu.cn/", sourceUrl: "https://gjwh.hlju.edu.cn/", location: "Harbin", focus: "languages, law, Chinese language, computer science, business, and humanities", majors: ["Chinese Language", "Law", "Computer Science", "Business"] },
  { name: "Henan University", website: "https://www.henu.edu.cn/", sourceUrl: "https://sie.henu.edu.cn/", location: "Kaifeng", focus: "humanities, education, medicine, business, sciences, and Chinese language", majors: ["Education", "Medicine", "Chinese Language", "Business"] },
  { name: "Henan University of Chinese Medicine", website: "https://www.hactcm.edu.cn/", sourceUrl: "https://gjjyxy.hactcm.edu.cn/", location: "Zhengzhou", focus: "traditional Chinese medicine, acupuncture, rehabilitation, nursing, and pharmacy", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Henan University of Technology", website: "https://www.haut.edu.cn/", sourceUrl: "https://sie.haut.edu.cn/", location: "Zhengzhou", focus: "food science, grain engineering, mechanical engineering, computer science, and business", majors: ["Food Science", "Engineering", "Computer Science", "Business"] },
  { name: "Hohai University", website: "https://en.hhu.edu.cn/", sourceUrl: "https://cie.hhu.edu.cn/", location: "Nanjing", focus: "water resources, civil engineering, environmental science, energy, computer science, and management", majors: ["Water Resources", "Civil Engineering", "Environmental Science", "Engineering"] },
  { name: "Huazhong Agricultural University", website: "https://www.hzau.edu.cn/", sourceUrl: "https://fao.hzau.edu.cn/", location: "Wuhan", focus: "agriculture, life sciences, food science, veterinary medicine, ecology, and business", majors: ["Agriculture", "Life Sciences", "Food Science", "Business"] },
  { name: "Hubei University", website: "https://www.hubu.edu.cn/", sourceUrl: "https://sie.hubu.edu.cn/", location: "Wuhan", focus: "education, humanities, business, computer science, materials, and Chinese language", majors: ["Education", "Chinese Language", "Computer Science", "Business"] },
  { name: "Hubei University of Chinese Medicine", website: "https://www.hbtcm.edu.cn/", sourceUrl: "https://iec.hbtcm.edu.cn/", location: "Wuhan", focus: "traditional Chinese medicine, acupuncture, pharmacy, nursing, and rehabilitation", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Hunan Normal University", website: "https://www.hunnu.edu.cn/", sourceUrl: "https://oiec.hunnu.edu.cn/", location: "Changsha", focus: "education, Chinese language, humanities, sciences, music, arts, and business", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Hunan University", website: "https://www-en.hnu.edu.cn/", sourceUrl: "https://gjxy.hnu.edu.cn/", location: "Changsha", focus: "engineering, business, design, computer science, architecture, and Chinese language", majors: ["Engineering", "Business", "Computer Science", "Architecture"] },
  { name: "Inner Mongolia Agricultural University", website: "https://www.imau.edu.cn/", sourceUrl: "https://gjjy.imau.edu.cn/", location: "Hohhot", focus: "agriculture, animal science, forestry, ecology, food science, and engineering", majors: ["Agriculture", "Animal Science", "Forestry", "Engineering"] },
  { name: "Inner Mongolia Normal University", website: "https://www.imnu.edu.cn/", sourceUrl: "https://gjjy.imnu.edu.cn/", location: "Hohhot", focus: "education, Chinese language, Mongolian studies, humanities, sciences, and arts", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Inner Mongolia University", website: "https://www.imu.edu.cn/", sourceUrl: "https://sie.imu.edu.cn/", location: "Hohhot", focus: "Mongolian studies, ecology, biology, computer science, humanities, and business", majors: ["Chinese Language", "Ecology", "Computer Science", "Business"] },
  { name: "Jiangsu University", website: "https://eng.ujs.edu.cn/", sourceUrl: "https://oec.ujs.edu.cn/", location: "Zhenjiang", focus: "engineering, vehicles, agriculture machinery, medicine, computer science, and business", majors: ["Engineering", "Computer Science", "Medicine", "Business"] },
  { name: "Jiangxi Agricultural University", website: "https://www.jxau.edu.cn/", sourceUrl: "https://gjjy.jxau.edu.cn/", location: "Nanchang", focus: "agriculture, forestry, food science, life sciences, engineering, and business", majors: ["Agriculture", "Forestry", "Food Science", "Business"] },
  { name: "Jiangxi Normal University", website: "https://www.jxnu.edu.cn/", sourceUrl: "https://gjjyxy.jxnu.edu.cn/", location: "Nanchang", focus: "education, Chinese language, humanities, sciences, arts, and business", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Jiangxi University of Finance and Economics", website: "https://www.jxufe.edu.cn/", sourceUrl: "https://oec.jxufe.edu.cn/", location: "Nanchang", focus: "finance, economics, accounting, business, statistics, and management", majors: ["Finance", "Economics", "Accounting", "Business"] },
  { name: "Jilin Agricultural University", website: "https://www.jlau.edu.cn/", sourceUrl: "https://gjxy.jlau.edu.cn/", location: "Changchun", focus: "agriculture, food science, veterinary medicine, life sciences, engineering, and business", majors: ["Agriculture", "Food Science", "Animal Science", "Business"] },
  { name: "Jilin Normal University", website: "https://www.jlnu.edu.cn/", sourceUrl: "https://gjjy.jlnu.edu.cn/", location: "Siping", focus: "education, Chinese language, humanities, sciences, arts, and business", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Jinan University", website: "https://english.jnu.edu.cn/", sourceUrl: "https://admission.jnu.edu.cn/", location: "Guangzhou", focus: "business, medicine, journalism, Chinese language, computer science, and international education", majors: ["Business", "Medicine", "Communication", "Chinese Language"] },
  { name: "Kunming Medical University", website: "https://www.kmmu.edu.cn/", sourceUrl: "https://gjxy.kmmu.edu.cn/", location: "Kunming", focus: "clinical medicine, public health, pharmacy, nursing, and tropical medicine", majors: ["Medicine", "Public Health", "Pharmacy", "Nursing"] },
  { name: "Kunming University of Science and Technology", website: "https://www.kmust.edu.cn/", sourceUrl: "https://gjxy.kmust.edu.cn/", location: "Kunming", focus: "engineering, metallurgy, environmental science, computer science, architecture, and medicine", majors: ["Engineering", "Computer Science", "Architecture", "Medicine"] },
  { name: "Lanzhou Jiaotong University", website: "https://www.lzjtu.edu.cn/", sourceUrl: "https://gjjy.lzjtu.edu.cn/", location: "Lanzhou", focus: "railway engineering, transport, civil engineering, environmental science, computer science, and management", majors: ["Transport", "Civil Engineering", "Engineering", "Computer Science"] },
  { name: "Lanzhou University of Technology", website: "https://www.lut.edu.cn/", sourceUrl: "https://gjjy.lut.edu.cn/", location: "Lanzhou", focus: "mechanical engineering, materials, energy, civil engineering, computer science, and business", majors: ["Engineering", "Materials Science", "Computer Science", "Business"] },
  { name: "Liaoning Normal University", website: "https://www.lnnu.edu.cn/", sourceUrl: "https://gjy.lnnu.edu.cn/", location: "Dalian", focus: "education, Chinese language, psychology, humanities, sciences, and arts", majors: ["Education", "Chinese Language", "Psychology", "Business"] },
  { name: "Liaoning Shihua University", website: "https://www.lnpu.edu.cn/", sourceUrl: "https://gjy.lnpu.edu.cn/", location: "Fushun", focus: "petrochemical engineering, chemical engineering, mechanical engineering, computer science, and business", majors: ["Chemical Engineering", "Engineering", "Computer Science", "Business"] },
  { name: "Liaoning Technical University", website: "https://www.lntu.edu.cn/", sourceUrl: "https://gjjl.lntu.edu.cn/", location: "Fuxin", focus: "mining, safety engineering, surveying, civil engineering, computer science, and management", majors: ["Mining Engineering", "Civil Engineering", "Computer Science", "Business"] },
  { name: "Liaoning University of Technology", website: "https://www.lnut.edu.cn/", sourceUrl: "https://gjjy.lnut.edu.cn/", location: "Jinzhou", focus: "vehicle engineering, mechanical engineering, computer science, electrical engineering, and business", majors: ["Engineering", "Vehicle Engineering", "Computer Science", "Business"] },
  { name: "Ludong University", website: "https://www.ldu.edu.cn/", sourceUrl: "https://www.ldu.edu.cn/gjjl.htm", location: "Yantai", focus: "education, Chinese language, agriculture, engineering, humanities, and business", majors: ["Education", "Chinese Language", "Engineering", "Business"] },
  { name: "Minzu University of China", website: "https://www.muc.edu.cn/", sourceUrl: "https://international.muc.edu.cn/", location: "Beijing", focus: "ethnic studies, Chinese language, humanities, law, economics, music, and arts", majors: ["Chinese Language", "Ethnic Studies", "Law", "Arts"] },
  { name: "Nanchang Hangkong University", website: "https://www.nchu.edu.cn/", sourceUrl: "https://sie.nchu.edu.cn/", location: "Nanchang", focus: "aerospace engineering, materials, mechanical engineering, computer science, and business", majors: ["Aerospace Engineering", "Engineering", "Computer Science", "Business"] },
  { name: "Nanchang University", website: "https://english.ncu.edu.cn/", sourceUrl: "https://iec.ncu.edu.cn/", location: "Nanchang", focus: "medicine, engineering, food science, materials, computer science, and business", majors: ["Medicine", "Engineering", "Food Science", "Business"] },
  { name: "Nanjing Agricultural University", website: "https://english.njau.edu.cn/", sourceUrl: "https://coie.njau.edu.cn/", location: "Nanjing", focus: "agriculture, life sciences, food science, veterinary medicine, plant sciences, and business", majors: ["Agriculture", "Life Sciences", "Food Science", "Business"] },
  { name: "Nanjing University of Aeronautics and Astronautics", website: "https://iao.nuaa.edu.cn/", sourceUrl: "https://cie.nuaa.edu.cn/", location: "Nanjing", focus: "aerospace engineering, mechanical engineering, computer science, automation, and business", majors: ["Aerospace Engineering", "Engineering", "Computer Science", "Business"] },
  { name: "Nanjing University of Chinese Medicine", website: "https://english.njucm.edu.cn/", sourceUrl: "https://iec.njucm.edu.cn/", location: "Nanjing", focus: "traditional Chinese medicine, acupuncture, pharmacy, nursing, and rehabilitation", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Nanjing University of Information Science and Technology", website: "https://en.nuist.edu.cn/", sourceUrl: "https://oec.nuist.edu.cn/", location: "Nanjing", focus: "atmospheric science, computer science, artificial intelligence, environmental science, and business", majors: ["Atmospheric Science", "Computer Science", "Artificial Intelligence", "Business"] },
  { name: "Ningbo University", website: "https://www.nbu.edu.cn/", sourceUrl: "https://iso.nbu.edu.cn/", location: "Ningbo", focus: "marine science, business, engineering, medicine, Chinese language, and law", majors: ["Marine Science", "Business", "Engineering", "Medicine"] },
  { name: "Ningxia University", website: "https://www.nxu.edu.cn/", sourceUrl: "https://gjy.nxu.edu.cn/", location: "Yinchuan", focus: "agriculture, engineering, Chinese language, humanities, ecology, and business", majors: ["Agriculture", "Engineering", "Chinese Language", "Business"] },
  { name: "North China Electric Power University", website: "https://english.ncepu.edu.cn/", sourceUrl: "https://iso.ncepu.edu.cn/", location: "Beijing", focus: "electrical engineering, energy, automation, environmental science, computer science, and management", majors: ["Electrical Engineering", "Energy Engineering", "Computer Science", "Business"] },
  { name: "Northeast Agricultural University", website: "https://www.neau.edu.cn/", sourceUrl: "https://gjjyxy.neau.edu.cn/", location: "Harbin", focus: "agriculture, animal science, food science, life sciences, engineering, and business", majors: ["Agriculture", "Animal Science", "Food Science", "Business"] },
  { name: "Northeast Dianli University", website: "https://www.neepu.edu.cn/", sourceUrl: "https://iec.neepu.edu.cn/", location: "Jilin", focus: "electrical engineering, energy, automation, computer science, chemical engineering, and business", majors: ["Electrical Engineering", "Energy Engineering", "Computer Science", "Business"] },
  { name: "Northeast Forestry University", website: "https://www.nefu.edu.cn/", sourceUrl: "https://sie.nefu.edu.cn/", location: "Harbin", focus: "forestry, ecology, landscape architecture, civil engineering, life sciences, and business", majors: ["Forestry", "Ecology", "Architecture", "Business"] },
  { name: "Northwest Normal University", website: "https://www.nwnu.edu.cn/", sourceUrl: "https://gjwhjl.nwnu.edu.cn/", location: "Lanzhou", focus: "education, Chinese language, humanities, sciences, psychology, and arts", majors: ["Education", "Chinese Language", "Psychology", "Arts"] },
  { name: "Northwest University", website: "https://english.nwu.edu.cn/", sourceUrl: "https://sie.nwu.edu.cn/", location: "Xi'an", focus: "archaeology, geology, economics, computer science, Chinese language, and business", majors: ["Archaeology", "Geosciences", "Computer Science", "Business"] },
  { name: "Qingdao University", website: "https://english.qdu.edu.cn/", sourceUrl: "https://istudy.qdu.edu.cn/", location: "Qingdao", focus: "medicine, engineering, textiles, business, Chinese language, and computer science", majors: ["Medicine", "Engineering", "Business", "Chinese Language"] },
  { name: "Qingdao University of Science and Technology", website: "https://en.qust.edu.cn/", sourceUrl: "https://gjc.qust.edu.cn/", location: "Qingdao", focus: "chemical engineering, materials, rubber engineering, computer science, and business", majors: ["Chemical Engineering", "Materials Science", "Computer Science", "Business"] },
  { name: "Qinghai University", website: "https://www.qhu.edu.cn/", sourceUrl: "https://gjjy.qhu.edu.cn/", location: "Xining", focus: "medicine, agriculture, ecology, water resources, engineering, and regional studies", majors: ["Medicine", "Agriculture", "Ecology", "Engineering"] },
  { name: "Shaanxi Normal University", website: "https://english.snnu.edu.cn/", sourceUrl: "https://iso.snnu.edu.cn/", location: "Xi'an", focus: "education, Chinese language, humanities, psychology, sciences, and arts", majors: ["Education", "Chinese Language", "Psychology", "Arts"] },
  { name: "Shandong Normal University", website: "https://www.sdnu.edu.cn/", sourceUrl: "https://www.sdnu.edu.cn/gjjl.htm", location: "Jinan", focus: "education, Chinese language, humanities, sciences, psychology, and business", majors: ["Education", "Chinese Language", "Psychology", "Business"] },
  { name: "Shandong University of Science and Technology", website: "https://www.sdust.edu.cn/", sourceUrl: "https://gjjl.sdust.edu.cn/", location: "Qingdao", focus: "mining, safety engineering, computer science, automation, surveying, and business", majors: ["Mining Engineering", "Computer Science", "Engineering", "Business"] },
  { name: "Shanghai Maritime University", website: "https://en.shmtu.edu.cn/", sourceUrl: "https://iec.shmtu.edu.cn/", location: "Shanghai", focus: "maritime studies, logistics, transport, engineering, business, and law", majors: ["Marine Science", "Transport", "Logistics", "Business"] },
  { name: "Shanghai Normal University", website: "https://www.shnu.edu.cn/", sourceUrl: "https://iao.shnu.edu.cn/", location: "Shanghai", focus: "education, Chinese language, humanities, tourism, business, and arts", majors: ["Education", "Chinese Language", "Tourism", "Business"] },
  { name: "Shanghai Ocean University", website: "https://www.shou.edu.cn/", sourceUrl: "https://iec.shou.edu.cn/", location: "Shanghai", focus: "marine science, aquaculture, food science, environmental science, logistics, and business", majors: ["Marine Science", "Food Science", "Environmental Science", "Business"] },
  { name: "Shanghai University of International Business and Economics", website: "https://www.suibe.edu.cn/", sourceUrl: "https://www.suibe.edu.cn/sis/", location: "Shanghai", focus: "international business, economics, finance, trade, law, and languages", majors: ["Business", "Economics", "Finance", "Law"] },
  { name: "Shanghai University of Political Science and Law", website: "https://www.shupl.edu.cn/", sourceUrl: "https://iso.shupl.edu.cn/", location: "Shanghai", focus: "law, politics, public administration, business law, and Chinese language", majors: ["Law", "International Relations", "Business", "Chinese Language"] },
  { name: "Shanghai University of Traditional Chinese Medicine", website: "https://www.shutcm.edu.cn/", sourceUrl: "https://iec.shutcm.edu.cn/", location: "Shanghai", focus: "traditional Chinese medicine, acupuncture, rehabilitation, pharmacy, and nursing", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Shantou University", website: "https://www.stu.edu.cn/", sourceUrl: "https://admission.stu.edu.cn/", location: "Shantou", focus: "medicine, business, engineering, design, journalism, and Chinese language", majors: ["Medicine", "Business", "Engineering", "Design"] },
  { name: "Shanxi University", website: "https://www.sxu.edu.cn/", sourceUrl: "https://sie.sxu.edu.cn/", location: "Taiyuan", focus: "sciences, humanities, Chinese language, computer science, business, and philosophy", majors: ["Chinese Language", "Computer Science", "Business", "Physics"] },
  { name: "Shenyang Aerospace University", website: "https://www.sau.edu.cn/", sourceUrl: "https://sau.ciss.org.cn/", location: "Shenyang", focus: "aerospace engineering, mechanical engineering, computer science, automation, and business", majors: ["Aerospace Engineering", "Engineering", "Computer Science", "Business"] },
  { name: "Shenyang Jianzhu University", website: "https://www.sjzu.edu.cn/", sourceUrl: "https://gjy.sjzu.edu.cn/", location: "Shenyang", focus: "architecture, civil engineering, urban planning, environmental engineering, and management", majors: ["Architecture", "Civil Engineering", "Engineering", "Business"] },
  { name: "Shenyang Normal University", website: "https://www.synu.edu.cn/", sourceUrl: "https://gjy.synu.edu.cn/", location: "Shenyang", focus: "education, Chinese language, humanities, sciences, arts, and business", majors: ["Education", "Chinese Language", "Arts", "Business"] },
  { name: "Shihezi University", website: "https://www.shzu.edu.cn/", sourceUrl: "https://gjjy.shzu.edu.cn/", location: "Shihezi", focus: "agriculture, medicine, engineering, business, Chinese language, and regional development", majors: ["Agriculture", "Medicine", "Engineering", "Business"] },
  { name: "Sichuan International Studies University", website: "https://www.sisu.edu.cn/", sourceUrl: "https://international.sisu.edu.cn/", location: "Chongqing", focus: "languages, translation, international communication, Chinese language, business, and tourism", majors: ["Chinese Language", "Translation", "Business", "Tourism"] },
  { name: "South China Agricultural University", website: "https://english.scau.edu.cn/", sourceUrl: "https://cie.scau.edu.cn/", location: "Guangzhou", focus: "agriculture, life sciences, food science, veterinary medicine, engineering, and business", majors: ["Agriculture", "Life Sciences", "Food Science", "Business"] },
  { name: "Southwest University", website: "https://www.swu.edu.cn/", sourceUrl: "https://gjxy.swu.edu.cn/", location: "Chongqing", focus: "education, psychology, agriculture, Chinese language, business, and computer science", majors: ["Education", "Psychology", "Agriculture", "Business"] },
  { name: "Southwest University of Finance and Economics", website: "https://e.swufe.edu.cn/", sourceUrl: "https://international.swufe.edu.cn/", location: "Chengdu", focus: "finance, economics, accounting, business analytics, management, and law", majors: ["Finance", "Economics", "Accounting", "Business"] },
  { name: "Taiyuan University of Technology", website: "https://www.tyut.edu.cn/", sourceUrl: "https://gjjyxy.tyut.edu.cn/", location: "Taiyuan", focus: "engineering, materials, mining, computer science, mechanical engineering, and business", majors: ["Engineering", "Materials Science", "Computer Science", "Business"] },
  { name: "Tianjin Foreign Studies University", website: "https://www.tjfsu.edu.cn/", sourceUrl: "https://ies.tjfsu.edu.cn/", location: "Tianjin", focus: "languages, translation, international communication, Chinese language, business, and tourism", majors: ["Chinese Language", "Translation", "Business", "Tourism"] },
  { name: "Tianjin Medical University", website: "https://www.tmu.edu.cn/", sourceUrl: "https://gs.tmu.edu.cn/", location: "Tianjin", focus: "clinical medicine, medical imaging, public health, pharmacy, and nursing", majors: ["Medicine", "Medical Imaging", "Public Health", "Nursing"] },
  { name: "Tianjin Polytechnic University", website: "https://www.tiangong.edu.cn/", sourceUrl: "https://gjxy.tiangong.edu.cn/", location: "Tianjin", focus: "textiles, materials, design, computer science, engineering, and business", majors: ["Textile Engineering", "Materials Science", "Design", "Business"] },
  { name: "Tianjin University of Finance and Economics", website: "https://www.tjufe.edu.cn/", sourceUrl: "https://intl.tjufe.edu.cn/", location: "Tianjin", focus: "finance, economics, accounting, business, statistics, and management", majors: ["Finance", "Economics", "Accounting", "Business"] },
  { name: "Tianjin University of Science and Technology", website: "https://www.tust.edu.cn/", sourceUrl: "https://sie.tust.edu.cn/", location: "Tianjin", focus: "food science, light industry, marine science, engineering, computer science, and business", majors: ["Food Science", "Marine Science", "Engineering", "Business"] },
  { name: "Tianjin University of Technology", website: "https://www.tjut.edu.cn/", sourceUrl: "https://gjjl.tjut.edu.cn/", location: "Tianjin", focus: "engineering, computer science, materials, management, design, and Chinese language", majors: ["Engineering", "Computer Science", "Materials Science", "Business"] },
  { name: "Tianjin University of Traditional Chinese Medicine", website: "https://www.tjutcm.edu.cn/", sourceUrl: "https://iec.tjutcm.edu.cn/", location: "Tianjin", focus: "traditional Chinese medicine, acupuncture, rehabilitation, pharmacy, and nursing", majors: ["Chinese Medicine", "Medicine", "Pharmacy", "Nursing"] },
  { name: "Tianjin Normal University", website: "https://www.tjnu.edu.cn/", sourceUrl: "https://gjjl.tjnu.edu.cn/", location: "Tianjin", focus: "education, Chinese language, psychology, humanities, sciences, and arts", majors: ["Education", "Chinese Language", "Psychology", "Arts"] },
  { name: "University of Chinese Academy of Sciences", website: "https://english.ucas.ac.cn/", sourceUrl: "https://iso.ucas.ac.cn/", location: "Beijing", focus: "science, engineering, computer science, life sciences, mathematics, and research training", majors: ["Computer Science", "Engineering", "Life Sciences", "Mathematics"] },
  { name: "University of Science and Technology Beijing", website: "https://en.ustb.edu.cn/", sourceUrl: "https://isc.ustb.edu.cn/", location: "Beijing", focus: "materials, metallurgy, engineering, computer science, automation, and business", majors: ["Materials Science", "Engineering", "Computer Science", "Business"] },
  { name: "University of Science and Technology Liaoning", website: "https://www.ustl.edu.cn/", sourceUrl: "https://gjjy.ustl.edu.cn/", location: "Anshan", focus: "metallurgy, materials, mechanical engineering, computer science, and business", majors: ["Materials Science", "Engineering", "Computer Science", "Business"] },
  { name: "University of Shanghai for Science and Technology", website: "https://en.usst.edu.cn/", sourceUrl: "https://isoe.usst.edu.cn/", location: "Shanghai", focus: "mechanical engineering, optical engineering, business, computer science, energy, and design", majors: ["Engineering", "Computer Science", "Business", "Design"] },
  { name: "Wenzhou Medical University", website: "https://en.wmu.edu.cn/", sourceUrl: "https://is.wmu.edu.cn/", location: "Wenzhou", focus: "clinical medicine, optometry, pharmacy, nursing, and biomedical sciences", majors: ["Medicine", "Optometry", "Pharmacy", "Nursing"] },
  { name: "Wenzhou University", website: "https://www.wzu.edu.cn/", sourceUrl: "https://cic.wzu.edu.cn/", location: "Wenzhou", focus: "education, engineering, business, Chinese language, design, and entrepreneurship", majors: ["Education", "Engineering", "Business", "Chinese Language"] },
  { name: "Wuhan Textile University", website: "https://www.wtu.edu.cn/", sourceUrl: "https://iec.wtu.edu.cn/", location: "Wuhan", focus: "textiles, fashion, design, materials, computer science, and business", majors: ["Textile Engineering", "Design", "Materials Science", "Business"] },
  { name: "Wuhan University of Technology", website: "https://english.whut.edu.cn/", sourceUrl: "https://sie.whut.edu.cn/", location: "Wuhan", focus: "materials, transport, engineering, automotive, computer science, and business", majors: ["Materials Science", "Engineering", "Transport", "Business"] },
  { name: "Wuyi University", website: "https://www.wyu.edu.cn/", sourceUrl: "https://gjxy.wyu.edu.cn/", location: "Jiangmen", focus: "engineering, business, Chinese language, textiles, design, and regional industry", majors: ["Engineering", "Business", "Chinese Language", "Design"] },
  { name: "Xiamen University of Technology", website: "https://www.xmut.edu.cn/", sourceUrl: "https://english.xmut.edu.cn/", location: "Xiamen", focus: "engineering, computer science, business, design, materials, and applied technology", majors: ["Engineering", "Computer Science", "Business", "Design"] },
  { name: "Xi'an International Studies University", website: "https://www.xisu.edu.cn/", sourceUrl: "https://sie.xisu.edu.cn/", location: "Xi'an", focus: "languages, translation, Chinese language, tourism, business, and international communication", majors: ["Chinese Language", "Translation", "Business", "Tourism"] },
  { name: "Xi'an Shiyou University", website: "https://www.xsyu.edu.cn/", sourceUrl: "https://gjjy.xsyu.edu.cn/", location: "Xi'an", focus: "petroleum engineering, chemical engineering, mechanical engineering, computer science, and business", majors: ["Petroleum Engineering", "Chemical Engineering", "Computer Science", "Business"] },
  { name: "Xiangtan University", website: "https://www.xtu.edu.cn/", sourceUrl: "https://international.xtu.edu.cn/", location: "Xiangtan", focus: "law, mathematics, materials, business, computer science, and Chinese language", majors: ["Law", "Mathematics", "Materials Science", "Business"] },
  { name: "Xinjiang Medical University", website: "https://www.xjmu.edu.cn/", sourceUrl: "https://gjjyxy.xjmu.edu.cn/", location: "Urumqi", focus: "clinical medicine, public health, pharmacy, nursing, and regional medical studies", majors: ["Medicine", "Public Health", "Pharmacy", "Nursing"] },
  { name: "Xinjiang Normal University", website: "https://www.xjnu.edu.cn/", sourceUrl: "https://gjwhjl.xjnu.edu.cn/", location: "Urumqi", focus: "education, Chinese language, Central Asian studies, humanities, sciences, and arts", majors: ["Education", "Chinese Language", "Regional Studies", "Arts"] },
  { name: "Xinjiang University", website: "https://www.xju.edu.cn/", sourceUrl: "https://gjwhjl.xju.edu.cn/", location: "Urumqi", focus: "engineering, Chinese language, Central Asian studies, computer science, business, and law", majors: ["Engineering", "Chinese Language", "Computer Science", "Business"] },
  { name: "Yangtze University", website: "https://www.yangtzeu.edu.cn/", sourceUrl: "https://international.yangtzeu.edu.cn/", location: "Jingzhou", focus: "petroleum engineering, agriculture, medicine, engineering, computer science, and business", majors: ["Petroleum Engineering", "Agriculture", "Medicine", "Business"] },
  { name: "Yangzhou University", website: "https://www.yzu.edu.cn/", sourceUrl: "https://coe.yzu.edu.cn/", location: "Yangzhou", focus: "agriculture, medicine, education, engineering, Chinese language, and business", majors: ["Agriculture", "Medicine", "Education", "Business"] },
  { name: "Yanshan University", website: "https://www.ysu.edu.cn/", sourceUrl: "https://ise.ysu.edu.cn/", location: "Qinhuangdao", focus: "mechanical engineering, materials, computer science, control engineering, and business", majors: ["Mechanical Engineering", "Materials Science", "Computer Science", "Business"] },
  { name: "Yantai University", website: "https://www.ytu.edu.cn/", sourceUrl: "https://iec.ytu.edu.cn/", location: "Yantai", focus: "law, pharmacy, engineering, business, Chinese language, and marine studies", majors: ["Law", "Pharmacy", "Engineering", "Business"] },
  { name: "Yunnan Agricultural University", website: "https://www.ynau.edu.cn/", sourceUrl: "https://gjxy.ynau.edu.cn/", location: "Kunming", focus: "agriculture, tea science, animal science, ecology, food science, and business", majors: ["Agriculture", "Food Science", "Animal Science", "Business"] },
  { name: "Yunnan Normal University", website: "https://www.ynnu.edu.cn/", sourceUrl: "https://gjy.ynnu.edu.cn/", location: "Kunming", focus: "education, Chinese language, Southeast Asian studies, tourism, humanities, and arts", majors: ["Education", "Chinese Language", "Regional Studies", "Tourism"] },
  { name: "Zhejiang Gongshang University", website: "https://www.zjgsu.edu.cn/", sourceUrl: "https://sie.zjgsu.edu.cn/", location: "Hangzhou", focus: "business, economics, statistics, food science, law, and Chinese language", majors: ["Business", "Economics", "Food Science", "Law"] },
  { name: "Zhejiang Ocean University", website: "https://www.zjou.edu.cn/", sourceUrl: "https://iso.zjou.edu.cn/", location: "Zhoushan", focus: "marine science, fisheries, ship engineering, food science, tourism, and business", majors: ["Marine Science", "Engineering", "Food Science", "Business"] },
  { name: "Zhejiang Sci-Tech University", website: "https://www.zstu.edu.cn/", sourceUrl: "https://sie.zstu.edu.cn/", location: "Hangzhou", focus: "textiles, fashion, materials, design, mechanical engineering, and business", majors: ["Textile Engineering", "Design", "Materials Science", "Business"] },
  { name: "Zhejiang University of Science and Technology", website: "https://www.zust.edu.cn/", sourceUrl: "https://ies.zust.edu.cn/", location: "Hangzhou", focus: "engineering, computer science, German-applied education, business, design, and Chinese language", majors: ["Engineering", "Computer Science", "Business", "Design"] },
  { name: "Zhejiang University of Technology", website: "https://www.zjut.edu.cn/", sourceUrl: "https://iec.zjut.edu.cn/", location: "Hangzhou", focus: "chemical engineering, computer science, pharmacy, business, materials, and design", majors: ["Chemical Engineering", "Computer Science", "Pharmacy", "Business"] },
  { name: "Zhengzhou University", website: "https://english.zzu.edu.cn/", sourceUrl: "https://international.zzu.edu.cn/", location: "Zhengzhou", focus: "medicine, engineering, chemistry, materials, business, and Chinese language", majors: ["Medicine", "Engineering", "Chemistry", "Business"] },
  { name: "Zhongnan University of Economics and Law", website: "https://english.zuel.edu.cn/", sourceUrl: "https://ies.zuel.edu.cn/", location: "Wuhan", focus: "law, economics, finance, accounting, business, and public administration", majors: ["Law", "Economics", "Finance", "Business"] }
];

const buildProfile = (seed: BulkAdmissionSeed): BulkEnrichment => ({
  website: seed.website,
  summary: `${seed.name} is an international-student destination in ${seed.location} with undergraduate pathways connected to ${seed.focus}.`,
  majors: seed.majors,
  applicationProfile: {
    sourceTitle: `${seed.name} international undergraduate admissions and international student office`,
    sourceDate: "Official university source or international application portal, checked 2026; annual undergraduate notice should be reconfirmed before submission.",
    sourceUrl: seed.sourceUrl,
    rankingHighlights: [
      `${seed.name} offers undergraduate study options connected to ${seed.focus}.`,
      `${seed.location} gives students a China study base with city, culture, travel, and internship context to compare before applying.`
    ],
    eligibility: [
      "Undergraduate applicants are generally expected to be non-Chinese citizens with valid passports, good health, and high school graduation or equivalent qualifications.",
      "Age, nationality-document rules, guardian documents for minors, health checks, and no-criminal-record requirements vary by annual notice.",
      "For the 2026 intake, many Chinese universities require CSCA results for undergraduate applicants; applicants should confirm the subject list for this school and major."
    ],
    languageRequirements: [
      "Chinese-taught undergraduate programs usually require an HSK certificate at the level specified by the program.",
      "English-taught undergraduate programs usually require IELTS, TOEFL, Duolingo, prior English-medium education proof, or an interview, depending on the university.",
      "Medical, art, architecture, and language-related programs may set additional portfolio, interview, science, or language thresholds."
    ],
    applicationSteps: [
      "Open the official source and confirm the current undergraduate program list, application deadline, CSCA requirements, tuition, and scholarship routes.",
      "Prepare passport, high school diploma or pre-graduation certificate, transcripts, language proof, physical examination, no-criminal-record certificate, and financial materials.",
      "Submit through the university's official international student application system or the portal linked from the international office.",
      "Track document review, interview or entrance assessment, scholarship decision, admission notice, JW form, visa, dormitory, and registration instructions."
    ],
    fees: {
      application: "Application fees vary by university and must be confirmed in the current official notice.",
      tuition: "Undergraduate tuition varies by major and language of instruction; confirm from the current official guide.",
      insurance: "International students in China are normally required to purchase approved medical insurance; many universities list about CNY 800/year.",
      accommodation: "Dormitory availability and fees vary by campus and room type; confirm before accepting admission."
    },
    programNotes: [
      "This is a source-traced first-pass undergraduate admissions profile for SilkStudy; exact annual PDF/prospectus details can be deepened school by school.",
      "Scholarships may include Chinese Government Scholarship, provincial/municipal scholarships, and university scholarships, but award level and eligibility must be verified for the target year.",
      "Students should compare language of instruction, city cost, campus location, internship access, scholarship probability, and visa timing before applying."
    ]
  }
});

export const bulkUndergraduateAdmissionEnrichments: Record<string, BulkEnrichment> = Object.fromEntries(
  seeds.map((seed) => [slugifyBulkName(seed.name), buildProfile(seed)])
);
