import type { University } from "@/lib/site-data";
import { universityProfileEnrichments } from "@/lib/catalog/university-profile-enrichments";

export type InternationalUniversitySource = {
  title: string;
  url: string;
  note: string;
  checkedAt: string;
};

export const internationalUniversitySources: InternationalUniversitySource[] = [
  {
    title: "China's Universities and Colleges Admitting International Students",
    url: "https://www.edu.cn/html/e/ChinaUniversity/indexSchool.html",
    note: "CUCAS / China Education Online city-based directory for institutions admitting international students.",
    checkedAt: "2026-06-01"
  },
  {
    title: "List of 279 China Universities Admitting Chinese Government Scholarship Students",
    url: "https://feature.cucas.cn/index/detail/1/1488",
    note: "CSC host-university list used as the first broad directory baseline. It is a scholarship-eligible subset, not the final full national admissions registry.",
    checkedAt: "2026-06-01"
  }
];

export const cscInternationalUniversityNames = [
  "Anhui Agricultural University",
  "Anhui Medical University",
  "Anhui Normal University",
  "Anhui University",
  "Anshan Normal University",
  "Anshan Normal University",
  "Beihua University",
  "Beijing Film Academy",
  "Beijing Foreign Studies University",
  "Beijing Forestry University",
  "Beijing Institute of Technology",
  "Beijing International Studies University",
  "Beijing Jiaotong University",
  "Beijing Language and Culture University",
  "Beijing Normal University",
  "Beijing Sport University",
  "Beijing Technology and Business University",
  "Beijing University of Chemical Technology",
  "Beijing University of Chinese Medicine",
  "Beijing University of Posts and Telecommunications",
  "Beijing University of Technology",
  "Bohai University",
  "Capital Institute of Physical Education",
  "Capital Medical University",
  "Capital Normal University",
  "Capital University of Economics and Business",
  "Central Academy of Fine Arts",
  "Central China Normal University",
  "Central Conservatory of Music",
  "Central South University",
  "Central University of Finance and Economics",
  "Chang'an University",
  "Changchun University",
  "Changchun University of Chinese Medicine",
  "Changchun University of Science and Technology",
  "Changsha University of Science and Technology",
  "Chengdu University of Traditional Chinese Medicine",
  "China Academy of Art",
  "China Agricultural University",
  "China Conservatory of Music",
  "China Foreign Affairs University",
  "China Medical University",
  "China Pharmaceutical University",
  "China Three Gorges University",
  "China University of Geosciences Beijing",
  "China University of Geosciences Wuhan",
  "China University of Mining and Technology",
  "China University of Petroleum Beijing",
  "China University of Petroleum Huadong",
  "China University of Political Science and Law",
  "China Youth University of Political Studies",
  "Chongqing Jiaotong University",
  "Chongqing Medical University",
  "Chongqing Medical University",
  "Chongqing University",
  "Chongqing University of Posts and Telecommunications",
  "Communication University of China",
  "Dalian Jiaotong University",
  "Dalian Maritime University",
  "Dalian Medical University",
  "Dalian Polytechnic University",
  "Dalian University of Foreign Languages",
  "Dalian University of Technology",
  "Donghua University",
  "East China Normal University",
  "East China University of Political Science and Law",
  "East China University of Science and Technology",
  "Fudan University",
  "Fujian Agriculture and Forestry University",
  "Fujian Medical University",
  "Fujian Normal University",
  "Fujian University of Technology",
  "Fuzhou University",
  "Gannan Normal University",
  "Guangdong University of Foreign Studies",
  "Guangdong University of Finance and Economics",
  "Guangxi Medical University",
  "Guangxi Normal University",
  "Guangxi Teachers Education University",
  "Guangxi University",
  "Guangxi University for Nationalities",
  "Guangzhou Medical University",
  "Guangzhou University of Chinese Medicine",
  "Guilin University of Electronic Technology",
  "Guizhou Minzu University",
  "Guizhou Normal University",
  "Guizhou University",
  "Hainan Normal University",
  "Hainan University",
  "Hangzhou Normal University",
  "Hangzhou Normal University",
  "Harbin Institute of Technology",
  "Harbin Medical University",
  "Harbin Normal University",
  "Harbin University of Science and Technology",
  "Hebei Medical University",
  "Hebei Normal University",
  "Hebei University",
  "Hebei University of Economics and Business",
  "Hebei University of Technology",
  "Hefei University",
  "Hefei University of Technology",
  "Heihe University",
  "Heilongjiang University",
  "Heilongjiang University of Chinese Medicine",
  "Henan University",
  "Henan University of Chinese Medicine",
  "Henan University of Technology",
  "Hohai University",
  "Huangshan University",
  "Huazhong Agricultural University",
  "Huazhong University of Science and Technology",
  "Hubei University",
  "Hubei University of Chinese Medicine",
  "Hunan Normal University",
  "Hunan University",
  "Hunan University of Technology",
  "Inner Mongolia Agricultural University",
  "Inner Mongolia Normal University",
  "Inner Mongolia University",
  "Inner Mongolia University for Nationalities",
  "Inner Mongolia University of Technology",
  "Inner Mongolia University of Technology",
  "Jiangnan University",
  "Jiangsu University",
  "Jiangsu University of Science and Technology",
  "Jiangxi Agricultural University",
  "Jiangxi Normal University",
  "Jiangxi University of Finance and Economics",
  "Jiangxi University of Traditional Chinese Medicine",
  "Jilin Agricultural University",
  "Jilin Normal University",
  "Jilin University",
  "Jinan University",
  "Jingdezhen Ceramic Institute",
  "Kunming Medical University",
  "Kunming University of Science and Technology",
  "Lanzhou Jiaotong University",
  "Lanzhou University",
  "Lanzhou University of Technology",
  "Liaoning Medical University",
  "Liaoning Normal University",
  "Liaoning Shihua University",
  "Liaoning Technical University",
  "Liaoning University",
  "Liaoning University of Technology",
  "Liaoning University of Traditional Chinese Medicine",
  "Ludong University",
  "Lu Xun Academy of Fine Arts",
  "Minzu University of China",
  "Mudanjiang Normal University",
  "Nanchang Hangkong University",
  "Nanchang University",
  "Nanjing Agricultural University",
  "Nanjing Agricultural University",
  "Nanjing Normal University",
  "Nanjing University",
  "Nanjing University of Aeronautics and Astronautics",
  "Nanjing University of Chinese Medicine",
  "Nanjing University of Information Science and Technology",
  "Nanjing University of Science and Technology",
  "Nanjing University of the Arts",
  "Nankai University",
  "Ningbo University",
  "Ningbo University of Technology",
  "Ningxia Medical University",
  "Ningxia University",
  "North China Electric Power University",
  "Northeast Agricultural University",
  "Northeast Dianli University",
  "Northeast Forestry University",
  "Northeast Normal University",
  "Northeastern University",
  "Northwest A&F University",
  "Northwestern Polytechnical University",
  "Northwest Normal University",
  "Northwest University",
  "Ocean University of China",
  "Peking University",
  "Qingdao University",
  "Qingdao University of Science and Technology",
  "Qinghai Nationalities University",
  "Qinghai University",
  "Qiqihar University",
  "Renmin University of China",
  "Shaanxi Normal University",
  "Shaanxi University of Chinese Medicine",
  "Shandong Normal University",
  "Shandong University",
  "Shandong University of Science and Technology",
  "Shandong University of Technology",
  "Shanghai Conservatory of Music",
  "Shanghai International Studies University",
  "Shanghai Jiao Tong University",
  "Shanghai Maritime University",
  "Shanghai Normal University",
  "Shanghai Ocean University",
  "Shanghai University",
  "Shanghai University of Finance and Economics",
  "Shanghai University of International Business and Economics",
  "Shanghai University of Political Science and Law",
  "Shanghai University of Sport",
  "Shanghai University of Traditional Chinese Medicine",
  "Shantou University",
  "Shanxi University",
  "Shenyang Aerospace University",
  "Shenyang Jianzhu University",
  "Shenyang Ligong University",
  "Shenyang Normal University",
  "Shenyang University of Technology",
  "Shihezi University",
  "Shenzhen University",
  "Sichuan International Studies University",
  "Sichuan University",
  "Soochow University",
  "South China Agricultural University",
  "South China Normal University",
  "South China University of Technology",
  "Southeast University",
  "Southern Medical University",
  "Southwest Jiaotong University",
  "Southwest University",
  "Southwest University of Political Science and Law",
  "Southwest University of Finance and Economics",
  "Southwestern University of Finance and Economics",
  "Sun Yat-sen University",
  "Taiyuan University of Technology",
  "The Central Academy of Drama",
  "The Graduate School of the Chinese Academy of Agricultural Sciences",
  "Tianjin Foreign Studies University",
  "Tianjin Medical University",
  "Tianjin Polytechnic University",
  "Tianjin University",
  "Tianjin University of Finance and Economics",
  "Tianjin University of Science and Technology",
  "Tianjin University of Technology",
  "Tianjin University of Technology and Education",
  "Tianjin University of Traditional Chinese Medicine",
  "Tianjin Normal University",
  "Tongji University",
  "Tsinghua University",
  "University of Chinese Academy of Sciences",
  "University of Electronic Science and Technology of China",
  "University of International Business and Economics",
  "University of Jinan",
  "University of Science and Technology of China",
  "University of Science and Technology Beijing",
  "University of Science and Technology Liaoning",
  "University of Shanghai for Science and Technology",
  "Wenzhou Medical University",
  "Wenzhou-Kean University",
  "Wenzhou University",
  "Wuhan Institute of Physical Education",
  "Wuhan Textile University",
  "Wuhan University",
  "Wuhan University of Technology",
  "Wuyi University",
  "Xiamen University",
  "Xiamen University of Technology",
  "Xi'an International Studies University",
  "Xi'an Jiaotong University",
  "Xi'an Shiyou University",
  "Xiangtan University",
  "Xidian University",
  "Xinjiang Medical University",
  "Xinjiang Normal University",
  "Xinjiang University",
  "Yanbian University",
  "Yangtze University",
  "Yangzhou University",
  "Yanshan University",
  "Yantai University",
  "Yunnan Agricultural University",
  "Yunnan Normal University",
  "Yunnan University",
  "Yunnan University of Finance and Economics",
  "Yunnan University of Nationalities",
  "Zhejiang Gongshang University",
  "Zhejiang Normal University",
  "Zhejiang Ocean University",
  "Zhejiang Sci-Tech University",
  "Zhejiang University",
  "Zhejiang University of Science and Technology",
  "Zhejiang University of Technology",
  "Zhengzhou University",
  "Zhongnan University of Economics and Law"
] as const;

export function slugifyUniversityName(name: string) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

type CatalogLocation = {
  hint: string;
  citySlug: string;
  provinceSlug: string;
  location: string;
};

const locationHints: CatalogLocation[] = [
  { hint: "Beijing", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Capital", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Peking", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Tsinghua", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Renmin", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Beihang University", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "China Agricultural University", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Central University of Finance and Economics", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Shanghai", citySlug: "shanghai", provinceSlug: "shanghai", location: "Shanghai" },
  { hint: "Tongji", citySlug: "shanghai", provinceSlug: "shanghai", location: "Shanghai" },
  { hint: "Fudan", citySlug: "shanghai", provinceSlug: "shanghai", location: "Shanghai" },
  { hint: "East China Normal University", citySlug: "shanghai", provinceSlug: "shanghai", location: "Shanghai" },
  { hint: "Donghua University", citySlug: "shanghai", provinceSlug: "shanghai", location: "Shanghai" },
  { hint: "Tianjin", citySlug: "tianjin", provinceSlug: "tianjin", location: "Tianjin" },
  { hint: "Nankai", citySlug: "tianjin", provinceSlug: "tianjin", location: "Tianjin" },
  { hint: "Nanjing", citySlug: "nanjing", provinceSlug: "jiangsu", location: "Nanjing" },
  { hint: "Southeast University", citySlug: "nanjing", provinceSlug: "jiangsu", location: "Nanjing" },
  { hint: "Jiangsu", citySlug: "nanjing", provinceSlug: "jiangsu", location: "Jiangsu" },
  { hint: "Jiangnan", citySlug: "wuxi", provinceSlug: "jiangsu", location: "Wuxi" },
  { hint: "Soochow", citySlug: "suzhou", provinceSlug: "jiangsu", location: "Suzhou" },
  { hint: "Yangzhou", citySlug: "yangzhou", provinceSlug: "jiangsu", location: "Yangzhou" },
  { hint: "Hangzhou", citySlug: "hangzhou", provinceSlug: "zhejiang", location: "Hangzhou" },
  { hint: "Zhejiang", citySlug: "hangzhou", provinceSlug: "zhejiang", location: "Zhejiang" },
  { hint: "Ningbo", citySlug: "ningbo", provinceSlug: "zhejiang", location: "Ningbo" },
  { hint: "Wenzhou", citySlug: "wenzhou", provinceSlug: "zhejiang", location: "Wenzhou" },
  { hint: "Guangzhou", citySlug: "guangzhou", provinceSlug: "guangdong", location: "Guangzhou" },
  { hint: "Guangdong", citySlug: "guangzhou", provinceSlug: "guangdong", location: "Guangdong" },
  { hint: "Shenzhen University", citySlug: "shenzhen", provinceSlug: "guangdong", location: "Shenzhen" },
  { hint: "South China", citySlug: "guangzhou", provinceSlug: "guangdong", location: "Guangzhou" },
  { hint: "Southern Medical", citySlug: "guangzhou", provinceSlug: "guangdong", location: "Guangzhou" },
  { hint: "Shantou", citySlug: "shantou", provinceSlug: "guangdong", location: "Shantou" },
  { hint: "Wuyi", citySlug: "jiangmen", provinceSlug: "guangdong", location: "Jiangmen" },
  { hint: "Chongqing", citySlug: "chongqing", provinceSlug: "chongqing", location: "Chongqing" },
  { hint: "Wuhan", citySlug: "wuhan", provinceSlug: "hubei", location: "Wuhan" },
  { hint: "Hubei", citySlug: "wuhan", provinceSlug: "hubei", location: "Hubei" },
  { hint: "Huazhong", citySlug: "wuhan", provinceSlug: "hubei", location: "Wuhan" },
  { hint: "China Three Gorges", citySlug: "yichang", provinceSlug: "hubei", location: "Yichang" },
  { hint: "Yangtze", citySlug: "jingzhou", provinceSlug: "hubei", location: "Jingzhou" },
  { hint: "Xi'an", citySlug: "xian", provinceSlug: "shaanxi", location: "Xi'an" },
  { hint: "Xian", citySlug: "xian", provinceSlug: "shaanxi", location: "Xi'an" },
  { hint: "Shaanxi", citySlug: "xian", provinceSlug: "shaanxi", location: "Shaanxi" },
  { hint: "Chang'an", citySlug: "xian", provinceSlug: "shaanxi", location: "Xi'an" },
  { hint: "Northwestern Polytechnical University", citySlug: "xian", provinceSlug: "shaanxi", location: "Xi'an" },
  { hint: "Northwest University", citySlug: "xian", provinceSlug: "shaanxi", location: "Xi'an" },
  { hint: "Xidian", citySlug: "xian", provinceSlug: "shaanxi", location: "Xi'an" },
  { hint: "Chengdu", citySlug: "chengdu", provinceSlug: "sichuan", location: "Chengdu" },
  { hint: "University of Electronic Science and Technology of China", citySlug: "chengdu", provinceSlug: "sichuan", location: "Chengdu" },
  { hint: "Sichuan", citySlug: "chengdu", provinceSlug: "sichuan", location: "Sichuan" },
  { hint: "Southwest University of Political Science and Law", citySlug: "chongqing", provinceSlug: "chongqing", location: "Chongqing" },
  { hint: "Southwest", citySlug: "chengdu", provinceSlug: "sichuan", location: "Chengdu" },
  { hint: "Xiamen", citySlug: "xiamen", provinceSlug: "fujian", location: "Xiamen" },
  { hint: "Fujian", citySlug: "fuzhou", provinceSlug: "fujian", location: "Fujian" },
  { hint: "Fuzhou", citySlug: "fuzhou", provinceSlug: "fujian", location: "Fuzhou" },
  { hint: "Harbin", citySlug: "harbin", provinceSlug: "heilongjiang", location: "Harbin" },
  { hint: "Heilongjiang", citySlug: "harbin", provinceSlug: "heilongjiang", location: "Heilongjiang" },
  { hint: "Heihe", citySlug: "heihe", provinceSlug: "heilongjiang", location: "Heihe" },
  { hint: "Mudanjiang", citySlug: "mudanjiang", provinceSlug: "heilongjiang", location: "Mudanjiang" },
  { hint: "Qiqihar", citySlug: "qiqihar", provinceSlug: "heilongjiang", location: "Qiqihar" },
  { hint: "Jinan", citySlug: "jinan", provinceSlug: "shandong", location: "Jinan" },
  { hint: "Shandong", citySlug: "jinan", provinceSlug: "shandong", location: "Shandong" },
  { hint: "Qingdao", citySlug: "qingdao", provinceSlug: "shandong", location: "Qingdao" },
  { hint: "Yantai", citySlug: "yantai", provinceSlug: "shandong", location: "Yantai" },
  { hint: "Ocean University of China", citySlug: "qingdao", provinceSlug: "shandong", location: "Qingdao" },
  { hint: "China Pharmaceutical University", citySlug: "nanjing", provinceSlug: "jiangsu", location: "Nanjing" },
  { hint: "Hefei", citySlug: "hefei", provinceSlug: "anhui", location: "Hefei" },
  { hint: "Anhui", citySlug: "hefei", provinceSlug: "anhui", location: "Anhui" },
  { hint: "Huangshan", citySlug: "huangshan", provinceSlug: "anhui", location: "Huangshan" },
  { hint: "Changsha", citySlug: "changsha", provinceSlug: "hunan", location: "Changsha" },
  { hint: "Hunan University of Technology", citySlug: "zhuzhou", provinceSlug: "hunan", location: "Zhuzhou" },
  { hint: "Hunan", citySlug: "changsha", provinceSlug: "hunan", location: "Hunan" },
  { hint: "Xiangtan", citySlug: "xiangtan", provinceSlug: "hunan", location: "Xiangtan" },
  { hint: "Guangxi", citySlug: "nanning", provinceSlug: "guangxi", location: "Guangxi" },
  { hint: "Guilin", citySlug: "guilin", provinceSlug: "guangxi", location: "Guilin" },
  { hint: "Guizhou", citySlug: "guiyang", provinceSlug: "guizhou", location: "Guizhou" },
  { hint: "Hainan", citySlug: "haikou", provinceSlug: "hainan", location: "Hainan" },
  { hint: "Hebei", citySlug: "shijiazhuang", provinceSlug: "hebei", location: "Hebei" },
  { hint: "Yanshan", citySlug: "qinhuangdao", provinceSlug: "hebei", location: "Qinhuangdao" },
  { hint: "Henan", citySlug: "zhengzhou", provinceSlug: "henan", location: "Henan" },
  { hint: "Zhengzhou", citySlug: "zhengzhou", provinceSlug: "henan", location: "Zhengzhou" },
  { hint: "Inner Mongolia", citySlug: "hohhot", provinceSlug: "inner-mongolia", location: "Inner Mongolia" },
  { hint: "Jiangxi", citySlug: "nanchang", provinceSlug: "jiangxi", location: "Jiangxi" },
  { hint: "Nanchang", citySlug: "nanchang", provinceSlug: "jiangxi", location: "Nanchang" },
  { hint: "Gannan", citySlug: "ganzhou", provinceSlug: "jiangxi", location: "Ganzhou" },
  { hint: "Jingdezhen", citySlug: "jingdezhen", provinceSlug: "jiangxi", location: "Jingdezhen" },
  { hint: "Jilin", citySlug: "changchun", provinceSlug: "jilin", location: "Jilin" },
  { hint: "Changchun", citySlug: "changchun", provinceSlug: "jilin", location: "Changchun" },
  { hint: "Yanbian", citySlug: "yanji", provinceSlug: "jilin", location: "Yanji" },
  { hint: "Lanzhou", citySlug: "lanzhou", provinceSlug: "gansu", location: "Lanzhou" },
  { hint: "Gansu", citySlug: "lanzhou", provinceSlug: "gansu", location: "Gansu" },
  { hint: "Liaoning", citySlug: "shenyang", provinceSlug: "liaoning", location: "Liaoning" },
  { hint: "Shenyang", citySlug: "shenyang", provinceSlug: "liaoning", location: "Shenyang" },
  { hint: "Lu Xun Academy of Fine Arts", citySlug: "shenyang", provinceSlug: "liaoning", location: "Shenyang" },
  { hint: "Northeastern University", citySlug: "shenyang", provinceSlug: "liaoning", location: "Shenyang" },
  { hint: "China Medical University", citySlug: "shenyang", provinceSlug: "liaoning", location: "Shenyang" },
  { hint: "Dalian", citySlug: "dalian", provinceSlug: "liaoning", location: "Dalian" },
  { hint: "Anshan", citySlug: "anshan", provinceSlug: "liaoning", location: "Anshan" },
  { hint: "Bohai", citySlug: "jinzhou", provinceSlug: "liaoning", location: "Jinzhou" },
  { hint: "Ningxia", citySlug: "yinchuan", provinceSlug: "ningxia", location: "Ningxia" },
  { hint: "Qinghai", citySlug: "xining", provinceSlug: "qinghai", location: "Qinghai" },
  { hint: "Shanxi", citySlug: "taiyuan", provinceSlug: "shanxi", location: "Shanxi" },
  { hint: "Taiyuan", citySlug: "taiyuan", provinceSlug: "shanxi", location: "Taiyuan" },
  { hint: "Shihezi", citySlug: "shihezi", provinceSlug: "xinjiang", location: "Shihezi" },
  { hint: "Xinjiang", citySlug: "urumqi", provinceSlug: "xinjiang", location: "Xinjiang" },
  { hint: "Yunnan", citySlug: "kunming", provinceSlug: "yunnan", location: "Yunnan" },
  { hint: "Kunming", citySlug: "kunming", provinceSlug: "yunnan", location: "Kunming" },
  { hint: "Northwest A&F University", citySlug: "yangling", provinceSlug: "shaanxi", location: "Yangling" },
  { hint: "Minzu", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Foreign Affairs", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" },
  { hint: "Chinese Academy", citySlug: "beijing", provinceSlug: "beijing", location: "Beijing" }
];

export function inferCatalogLocation(name: string) {
  return locationHints.find((item) => name.includes(item.hint)) ?? {
    hint: "China",
    citySlug: "china",
    provinceSlug: "china",
    location: "China"
  };
}

export function inferCatalogCity(name: string) {
  return inferCatalogLocation(name).citySlug;
}

function inferCatalogMajors(name: string) {
  const majors = new Set<string>(["Chinese Language"]);

  if (/Medical|Medicine|Pharmaceutical|Chinese Medicine/i.test(name)) majors.add("Medicine");
  if (/Technology|Engineering|Jiaotong|Transport|Posts|Telecommunications|Electronic|Science and Technology|Electric|Aerospace|Mining|Petroleum|Chemical|Maritime|Ocean|Textile|Polytechnic|Geosciences/i.test(name)) {
    majors.add("Engineering");
    majors.add("Computer Science");
  }
  if (/Finance|Economics|Business|Trade|Commerce|Management/i.test(name)) majors.add("Business");
  if (/Normal|Education|Teacher/i.test(name)) majors.add("Chinese Language");
  if (/Agricultural|Forestry|Ocean|Marine/i.test(name)) majors.add("Marine Science");
  if (/Architecture|Jianzhu/i.test(name)) majors.add("Architecture");
  if (/Sport|Physical/i.test(name)) majors.add("Chinese Language");
  if (/Art|Music|Drama|Film/i.test(name)) majors.add("Chinese Language");

  if (majors.size < 3) majors.add("Business");
  if (majors.size < 3) majors.add("Engineering");

  return Array.from(majors).slice(0, 4);
}

function inferCatalogSummary(name: string, location: string, majors: string[]) {
  const focus = majors.filter((major) => major !== "Chinese Language").slice(0, 2).join(" and ") || "international education";
  return `${name} is included in the international-student university directory baseline for ${location}. Its initial profile is classified around ${focus}, with program, tuition, scholarship, website, and campus-life details queued for admissions-office verification.`;
}

export function buildCatalogUniversity(name: string, existing?: University): University {
  if (existing) return existing;

  const location = inferCatalogLocation(name);
  const enrichment = universityProfileEnrichments[slugifyUniversityName(name)];
  const majors = enrichment?.majors ?? inferCatalogMajors(name);

  return {
    slug: slugifyUniversityName(name),
    name,
    chineseName: name,
    qsRanking: 999,
    tuition: "Contact for latest tuition",
    location: location.location,
    citySlug: location.citySlug,
    provinceSlug: location.provinceSlug,
    foundedYear: 0,
    website: enrichment?.website ?? "#",
    internationalStudents: "Accepts international students",
    majors,
    scholarships: ["Chinese Government Scholarship", "University Scholarship"],
    summary: enrichment?.summary ?? inferCatalogSummary(name, location.location, majors),
    applicationProfile: enrichment?.applicationProfile,
    campusLife: {
      nearbyLiving: `${location.location} living and campus-neighborhood details are pending editorial verification.`,
      foodAndDailyLife: "Daily-life information will be expanded as the school profile is curated from official admissions and student-life sources.",
      tourism: `${location.location} travel and city context will be added in the next data enrichment pass.`,
      internshipsAndCareers: `Internship and career information depends on ${location.location} industry links, major choice, language ability, and university partnerships.`,
      transportAndSafety: "Transport and safety details should be checked against the latest university and city guidance."
    },
    reviews: []
  };
}

export function getCatalogUniversities(existingUniversities: University[]) {
  const bySlug = new Map(existingUniversities.map((university) => [university.slug, university]));
  const uniqueNames = Array.from(new Set(cscInternationalUniversityNames));

  return uniqueNames.map((name) => buildCatalogUniversity(name, bySlug.get(slugifyUniversityName(name))));
}

export function getCatalogUniversityBySlug(slug: string, existingUniversities: University[]) {
  return getCatalogUniversities(existingUniversities).find((university) => university.slug === slug);
}
