export type ChinaUniversityRanking = {
  rank: string;
  overallRank?: number;
  category: string;
  score?: number;
  source: string;
  sourceUrl: string;
  year: number;
  nameCn: string;
  nameEn: string;
  note?: string;
};

export const chinaUniversityRankings: Record<string, ChinaUniversityRanking> = {
  "anhui-agricultural-university": {
    rank: "143",
    overallRank: 143,
    category: "农业",
    score: 222,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "安徽农业大学",
    nameEn: "Anhui Agricultural University"
  },
  "anhui-medical-university": {
    rank: "医14",
    overallRank: 123,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "安徽医科大学",
    nameEn: "Anhui Medical University"
  },
  "anhui-normal-university": {
    rank: "145",
    overallRank: 145,
    category: "师范",
    score: 220.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "安徽师范大学",
    nameEn: "Anhui Normal University"
  },
  "anhui-university": {
    rank: "101",
    overallRank: 101,
    category: "综合",
    score: 273.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "安徽大学",
    nameEn: "Anhui University"
  },
  "anshan-normal-university": {
    rank: "478",
    overallRank: 478,
    category: "师范",
    score: 117.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "鞍山师范学院",
    nameEn: "Anshan Normal University"
  },
  "beihua-university": {
    rank: "308",
    overallRank: 308,
    category: "综合",
    score: 150.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北华大学",
    nameEn: "Beihua University"
  },
  "beijing-film-academy": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "北京电影学院",
    nameEn: "Beijing Film Academy",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "beijing-foreign-studies-university": {
    rank: "语1",
    overallRank: 79,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京外国语大学",
    nameEn: "Beijing Foreign Studies University"
  },
  "beijing-forestry-university": {
    rank: "83",
    overallRank: 83,
    category: "林业",
    score: 294.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京林业大学",
    nameEn: "Beijing Forestry University"
  },
  "beijing-institute-of-technology": {
    rank: "14",
    overallRank: 14,
    category: "理工",
    score: 595.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京理工大学",
    nameEn: "Beijing Institute of Technology"
  },
  "beijing-international-studies-university": {
    rank: "语7",
    overallRank: 213,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京第二外国语学院",
    nameEn: "Beijing International Studies University"
  },
  "beijing-jiaotong-university": {
    rank: "41",
    overallRank: 41,
    category: "理工",
    score: 381.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京交通大学",
    nameEn: "Beijing Jiaotong University"
  },
  "beijing-language-and-culture-university": {
    rank: "语5",
    overallRank: 119,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京语言大学",
    nameEn: "Beijing Language and Culture University"
  },
  "beijing-normal-university": {
    rank: "19",
    overallRank: 19,
    category: "师范",
    score: 553.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京师范大学",
    nameEn: "Beijing Normal University"
  },
  "beijing-sport-university": {
    rank: "体2",
    overallRank: 177,
    category: "体育",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京体育大学",
    nameEn: "Beijing Sport University"
  },
  "beijing-technology-and-business-university": {
    rank: "财11",
    overallRank: 129,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京工商大学",
    nameEn: "Beijing Technology and Business University"
  },
  "beijing-university-of-chemical-technology": {
    rank: "57",
    overallRank: 57,
    category: "理工",
    score: 345,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京化工大学",
    nameEn: "Beijing University of Chemical Technology"
  },
  "beijing-university-of-chinese-medicine": {
    rank: "中医1",
    overallRank: 63,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京中医药大学",
    nameEn: "Beijing University of Chinese Medicine"
  },
  "beijing-university-of-posts-and-telecommunications": {
    rank: "50",
    overallRank: 50,
    category: "理工",
    score: 360.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京邮电大学",
    nameEn: "Beijing University of Posts and Telecommunications"
  },
  "beijing-university-of-technology": {
    rank: "65",
    overallRank: 65,
    category: "理工",
    score: 341.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京工业大学",
    nameEn: "Beijing University of Technology"
  },
  "bohai-university": {
    rank: "285",
    overallRank: 285,
    category: "综合",
    score: 158.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "渤海大学",
    nameEn: "Bohai University"
  },
  "capital-institute-of-physical-education": {
    rank: "体3",
    overallRank: 262,
    category: "体育",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "首都体育学院",
    nameEn: "Capital University of Physical Education and Sports"
  },
  "capital-medical-university": {
    rank: "医2",
    overallRank: 37,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "首都医科大学",
    nameEn: "Capital Medical University"
  },
  "capital-normal-university": {
    rank: "100",
    overallRank: 100,
    category: "师范",
    score: 273.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "首都师范大学",
    nameEn: "Capital Normal University"
  },
  "capital-university-of-economics-and-business": {
    rank: "财9",
    overallRank: 113,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "首都经济贸易大学",
    nameEn: "Capital University of Economics & Business"
  },
  "central-academy-of-fine-arts": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "中央美术学院",
    nameEn: "Central Academy of Fine Arts",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "central-china-normal-university": {
    rank: "53",
    overallRank: 53,
    category: "师范",
    score: 355.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华中师范大学",
    nameEn: "Central China Normal University"
  },
  "central-conservatory-of-music": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "中央音乐学院",
    nameEn: "Central Conservatory of Music",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "central-south-university": {
    rank: "27",
    overallRank: 27,
    category: "综合",
    score: 497,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中南大学",
    nameEn: "Central South University"
  },
  "central-university-of-finance-and-economics": {
    rank: "财2",
    overallRank: 42,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中央财经大学",
    nameEn: "Central University of Finance and Economics"
  },
  "chang-an-university": {
    rank: "89",
    overallRank: 89,
    category: "理工",
    score: 282.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "长安大学",
    nameEn: "Chang'an University"
  },
  "changchun-university": {
    rank: "368",
    overallRank: 368,
    category: "综合",
    score: 134.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "长春大学",
    nameEn: "Changchun University"
  },
  "changchun-university-of-chinese-medicine": {
    rank: "中医15",
    overallRank: 207,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "长春中医药大学",
    nameEn: "Changchun University of Chinese Medicine"
  },
  "changchun-university-of-science-and-technology": {
    rank: "138",
    overallRank: 138,
    category: "理工",
    score: 230.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "长春理工大学",
    nameEn: "Changchun University of Science and Technology"
  },
  "changsha-university-of-science-and-technology": {
    rank: "135",
    overallRank: 135,
    category: "理工",
    score: 231.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "长沙理工大学",
    nameEn: "Changsha University of Science & Technology"
  },
  "chengdu-university-of-traditional-chinese-medicine": {
    rank: "中医6",
    overallRank: 121,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "成都中医药大学",
    nameEn: "Chengdu University of Traditional Chinese Medicine"
  },
  "china-academy-of-art": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "中国美术学院",
    nameEn: "China Academy of Art",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "china-agricultural-university": {
    rank: "24",
    overallRank: 24,
    category: "农业",
    score: 519.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国农业大学",
    nameEn: "China Agricultural University"
  },
  "china-conservatory-of-music": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "中国音乐学院",
    nameEn: "China Conservatory of Music",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "china-foreign-affairs-university": {
    rank: "语4",
    overallRank: 105,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "外交学院",
    nameEn: "China Foreign Affairs University"
  },
  "china-medical-university": {
    rank: "医6",
    overallRank: 62,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国医科大学",
    nameEn: "China Medical University (Shenyang)"
  },
  "china-pharmaceutical-university": {
    rank: "医10",
    overallRank: 88,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国药科大学",
    nameEn: "China Pharmaceutical University"
  },
  "china-three-gorges-university": {
    rank: "174",
    overallRank: 174,
    category: "综合",
    score: 205.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "三峡大学",
    nameEn: "China Three Gorges University"
  },
  "china-university-of-geosciences-beijing": {
    rank: "75",
    overallRank: 75,
    category: "理工",
    score: 314.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国地质大学（北京）",
    nameEn: "China University of Geosciences Beijing"
  },
  "china-university-of-geosciences-wuhan": {
    rank: "56",
    overallRank: 56,
    category: "理工",
    score: 350.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国地质大学（武汉）",
    nameEn: "China University of Geosciences"
  },
  "china-university-of-mining-and-technology": {
    rank: "67",
    overallRank: 67,
    category: "理工",
    score: 335.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国矿业大学",
    nameEn: "China University of Mining and Technology"
  },
  "china-university-of-petroleum-beijing": {
    rank: "62",
    overallRank: 62,
    category: "理工",
    score: 342.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国石油大学（北京）",
    nameEn: "China University of Petroleum, Beijing"
  },
  "china-university-of-petroleum-huadong": {
    rank: "73",
    overallRank: 73,
    category: "理工",
    score: 316.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国石油大学（华东）",
    nameEn: "China University of Petroleum (East China)"
  },
  "china-university-of-political-science-and-law": {
    rank: "政1",
    overallRank: 56,
    category: "政法",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国政法大学",
    nameEn: "China University of Political Science and Law"
  },
  "china-youth-university-of-political-studies": {
    rank: "未列入软科2026榜单",
    category: "未列入",
    source: "软科2026中国大学排名及分类榜检索",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "China Youth University of Political Studies",
    nameEn: "China Youth University of Political Studies",
    note: "未在软科2026中国大学排名/分类榜中检索到该校记录。"
  },
  "chongqing-jiaotong-university": {
    rank: "191",
    overallRank: 191,
    category: "理工",
    score: 195.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "重庆交通大学",
    nameEn: "Chongqing Jiaotong University"
  },
  "chongqing-medical-university": {
    rank: "医9",
    overallRank: 81,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "重庆医科大学",
    nameEn: "Chongqing Medical University"
  },
  "chongqing-university": {
    rank: "34",
    overallRank: 34,
    category: "综合",
    score: 436,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "重庆大学",
    nameEn: "Chongqing University"
  },
  "chongqing-university-of-posts-and-telecommunications": {
    rank: "147",
    overallRank: 147,
    category: "理工",
    score: 219.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "重庆邮电大学",
    nameEn: "Chongqing University of Posts and Telecommunications"
  },
  "communication-university-of-china": {
    rank: "语3",
    overallRank: 82,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国传媒大学",
    nameEn: "Communication University of China"
  },
  "dalian-jiaotong-university": {
    rank: "249",
    overallRank: 249,
    category: "理工",
    score: 171.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "大连交通大学",
    nameEn: "Dalian Jiaotong University"
  },
  "dalian-maritime-university": {
    rank: "113",
    overallRank: 113,
    category: "综合",
    score: 257.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "大连海事大学",
    nameEn: "Dalian Maritime University"
  },
  "dalian-medical-university": {
    rank: "医13",
    overallRank: 112,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "大连医科大学",
    nameEn: "Dalian Medical University"
  },
  "dalian-polytechnic-university": {
    rank: "211",
    overallRank: 211,
    category: "理工",
    score: 187,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "大连工业大学",
    nameEn: "Dalian Polytechnic University"
  },
  "dalian-university-of-foreign-languages": {
    rank: "语12",
    overallRank: 266,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "大连外国语大学",
    nameEn: "Dalian University of Foreign Languages"
  },
  "dalian-university-of-technology": {
    rank: "28",
    overallRank: 28,
    category: "理工",
    score: 495.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "大连理工大学",
    nameEn: "Dalian University of Technology"
  },
  "donghua-university": {
    rank: "72",
    overallRank: 72,
    category: "理工",
    score: 317.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东华大学",
    nameEn: "Donghua University"
  },
  "east-china-normal-university": {
    rank: "29",
    overallRank: 29,
    category: "师范",
    score: 469.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华东师范大学",
    nameEn: "East China Normal University"
  },
  "east-china-university-of-political-science-and-law": {
    rank: "政2",
    overallRank: 119,
    category: "政法",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华东政法大学",
    nameEn: "East China University of Political Science and Law"
  },
  "east-china-university-of-science-and-technology": {
    rank: "42",
    overallRank: 42,
    category: "理工",
    score: 380.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华东理工大学",
    nameEn: "East China University of Science and Technology"
  },
  "fudan-university": {
    rank: "5",
    overallRank: 5,
    category: "综合",
    score: 792.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "复旦大学",
    nameEn: "Fudan University"
  },
  "fujian-agriculture-and-forestry-university": {
    rank: "122",
    overallRank: 122,
    category: "农业",
    score: 243.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "福建农林大学",
    nameEn: "Fujian Agriculture and Forestry University"
  },
  "fujian-medical-university": {
    rank: "医15",
    overallRank: 126,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "福建医科大学",
    nameEn: "Fujian Medical University"
  },
  "fujian-normal-university": {
    rank: "90",
    overallRank: 90,
    category: "师范",
    score: 282.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "福建师范大学",
    nameEn: "Fujian Normal University"
  },
  "fujian-university-of-technology": {
    rank: "275",
    overallRank: 275,
    category: "理工",
    score: 162.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "福建理工大学",
    nameEn: "Fujian University of Technology"
  },
  "fuzhou-university": {
    rank: "77",
    overallRank: 77,
    category: "理工",
    score: 310.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "福州大学",
    nameEn: "Fuzhou University"
  },
  "gannan-normal-university": {
    rank: "252",
    overallRank: 252,
    category: "师范",
    score: 171,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "赣南师范大学",
    nameEn: "Gannan Normal University"
  },
  "guangdong-university-of-foreign-studies": {
    rank: "语6",
    overallRank: 129,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广东外语外贸大学",
    nameEn: "Guangdong University of Foreign Studies"
  },
  "guangdong-university-of-finance-and-economics": {
    rank: "财21",
    overallRank: 232,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广东财经大学",
    nameEn: "Guangdong University of Finance and Economics"
  },
  "guangxi-medical-university": {
    rank: "医18",
    overallRank: 151,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广西医科大学",
    nameEn: "Guangxi Medical University"
  },
  "guangxi-normal-university": {
    rank: "149",
    overallRank: 149,
    category: "师范",
    score: 217.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广西师范大学",
    nameEn: "Guangxi Normal University"
  },
  "guangxi-teachers-education-university": {
    rank: "295",
    overallRank: 295,
    category: "师范",
    score: 153.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南宁师范大学",
    nameEn: "Nanning Normal University"
  },
  "guangxi-university": {
    rank: "86",
    overallRank: 86,
    category: "综合",
    score: 288.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广西大学",
    nameEn: "Guangxi University"
  },
  "guangxi-university-for-nationalities": {
    rank: "民4",
    overallRank: 272,
    category: "民族",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广西民族大学",
    nameEn: "Guangxi University for Nationalities"
  },
  "guangzhou-medical-university": {
    rank: "医7",
    overallRank: 79,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广州医科大学",
    nameEn: "Guangzhou Medical University"
  },
  "guangzhou-university-of-chinese-medicine": {
    rank: "中医4",
    overallRank: 98,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "广州中医药大学",
    nameEn: "Guangzhou University of Chinese Medicine"
  },
  "guilin-university-of-electronic-technology": {
    rank: "183",
    overallRank: 183,
    category: "理工",
    score: 199.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "桂林电子科技大学",
    nameEn: "Guilin University of Electronic Technology"
  },
  "guizhou-minzu-university": {
    rank: "民7",
    overallRank: 280,
    category: "民族",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "贵州民族大学",
    nameEn: "Guizhou Minzu University"
  },
  "guizhou-normal-university": {
    rank: "220",
    overallRank: 220,
    category: "师范",
    score: 183.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "贵州师范大学",
    nameEn: "Guizhou Normal University"
  },
  "guizhou-university": {
    rank: "85",
    overallRank: 85,
    category: "综合",
    score: 291.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "贵州大学",
    nameEn: "Guizhou University"
  },
  "hainan-normal-university": {
    rank: "227",
    overallRank: 227,
    category: "师范",
    score: 180.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "海南师范大学",
    nameEn: "Hainan Normal University"
  },
  "hainan-university": {
    rank: "87",
    overallRank: 87,
    category: "综合",
    score: 286.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "海南大学",
    nameEn: "Hainan University"
  },
  "hangzhou-normal-university": {
    rank: "116",
    overallRank: 116,
    category: "师范",
    score: 254,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "杭州师范大学",
    nameEn: "Hangzhou Normal University"
  },
  "harbin-institute-of-technology": {
    rank: "12",
    overallRank: 12,
    category: "理工",
    score: 607.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "哈尔滨工业大学",
    nameEn: "Harbin Institute of Technology"
  },
  "harbin-medical-university": {
    rank: "医8",
    overallRank: 79,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "哈尔滨医科大学",
    nameEn: "Harbin Medical University"
  },
  "harbin-normal-university": {
    rank: "223",
    overallRank: 223,
    category: "师范",
    score: 182.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "哈尔滨师范大学",
    nameEn: "Harbin Normal University"
  },
  "harbin-university-of-science-and-technology": {
    rank: "214",
    overallRank: 214,
    category: "理工",
    score: 185,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "哈尔滨理工大学",
    nameEn: "Harbin University of Science and Technology"
  },
  "hebei-medical-university": {
    rank: "医12",
    overallRank: 109,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河北医科大学",
    nameEn: "Hebei Medical University"
  },
  "hebei-normal-university": {
    rank: "177",
    overallRank: 177,
    category: "师范",
    score: 204.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河北师范大学",
    nameEn: "Hebei Normal University"
  },
  "hebei-university": {
    rank: "130",
    overallRank: 130,
    category: "综合",
    score: 233.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河北大学",
    nameEn: "Hebei University"
  },
  "hebei-university-of-economics-and-business": {
    rank: "财23",
    overallRank: 253,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河北经贸大学",
    nameEn: "Hebei University of Economics and Business"
  },
  "hebei-university-of-technology": {
    rank: "107",
    overallRank: 107,
    category: "理工",
    score: 266.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河北工业大学",
    nameEn: "Hebei University of Technology"
  },
  "hefei-university": {
    rank: "316",
    overallRank: 316,
    category: "理工",
    score: 147.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "合肥大学",
    nameEn: "Hefei University"
  },
  "hefei-university-of-technology": {
    rank: "80",
    overallRank: 80,
    category: "理工",
    score: 304.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "合肥工业大学",
    nameEn: "Hefei University of Technology"
  },
  "heihe-university": {
    rank: "500+",
    category: "综合",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "黑河学院",
    nameEn: "Heihe University"
  },
  "heilongjiang-university": {
    rank: "155",
    overallRank: 155,
    category: "综合",
    score: 215.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "黑龙江大学",
    nameEn: "Heilongjiang University"
  },
  "heilongjiang-university-of-chinese-medicine": {
    rank: "中医16",
    overallRank: 211,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "黑龙江中医药大学",
    nameEn: "Heilongjiang University of Chinese Medicine"
  },
  "henan-university": {
    rank: "95",
    overallRank: 95,
    category: "综合",
    score: 279.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河南大学",
    nameEn: "Henan University"
  },
  "henan-university-of-chinese-medicine": {
    rank: "中医11",
    overallRank: 179,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河南中医药大学",
    nameEn: "Henan University of Chinese Medicine"
  },
  "henan-university-of-technology": {
    rank: "210",
    overallRank: 210,
    category: "理工",
    score: 187.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河南工业大学",
    nameEn: "Henan University of Technology"
  },
  "hohai-university": {
    rank: "63",
    overallRank: 63,
    category: "理工",
    score: 342,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "河海大学",
    nameEn: "Hohai University"
  },
  "huangshan-university": {
    rank: "481",
    overallRank: 481,
    category: "师范",
    score: 117,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "黄山学院",
    nameEn: "Huangshan University"
  },
  "huazhong-agricultural-university": {
    rank: "45",
    overallRank: 45,
    category: "农业",
    score: 375.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华中农业大学",
    nameEn: "Huazhong Agricultural University"
  },
  "huazhong-university-of-science-and-technology": {
    rank: "9",
    overallRank: 9,
    category: "综合",
    score: 638,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华中科技大学",
    nameEn: "Huazhong University of Science and Technology"
  },
  "hubei-university": {
    rank: "121",
    overallRank: 121,
    category: "综合",
    score: 243.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "湖北大学",
    nameEn: "Hubei University"
  },
  "hubei-university-of-chinese-medicine": {
    rank: "中医14",
    overallRank: 205,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "湖北中医药大学",
    nameEn: "Hubei University of Chinese Medicine"
  },
  "hunan-normal-university": {
    rank: "92",
    overallRank: 92,
    category: "师范",
    score: 280.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "湖南师范大学",
    nameEn: "Hunan Normal University"
  },
  "hunan-university": {
    rank: "31",
    overallRank: 31,
    category: "综合",
    score: 464.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "湖南大学",
    nameEn: "Hunan University"
  },
  "hunan-university-of-technology": {
    rank: "293",
    overallRank: 293,
    category: "理工",
    score: 154.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "湖南工业大学",
    nameEn: "Hunan University of Technology"
  },
  "inner-mongolia-agricultural-university": {
    rank: "212",
    overallRank: 212,
    category: "农业",
    score: 185.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "内蒙古农业大学",
    nameEn: "Inner Mongolia Agricultural University"
  },
  "inner-mongolia-normal-university": {
    rank: "220",
    overallRank: 220,
    category: "师范",
    score: 183.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "内蒙古师范大学",
    nameEn: "Inner Mongolia Normal University"
  },
  "inner-mongolia-university": {
    rank: "114",
    overallRank: 114,
    category: "综合",
    score: 256.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "内蒙古大学",
    nameEn: "Inner Mongolia University"
  },
  "inner-mongolia-university-for-nationalities": {
    rank: "民12",
    overallRank: 340,
    category: "民族",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "内蒙古民族大学",
    nameEn: "Inner Mongolia Minzu University"
  },
  "inner-mongolia-university-of-technology": {
    rank: "261",
    overallRank: 261,
    category: "理工",
    score: 168.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "内蒙古工业大学",
    nameEn: "Inner Mongolia University of Technology"
  },
  "jiangnan-university": {
    rank: "52",
    overallRank: 52,
    category: "综合",
    score: 355.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江南大学",
    nameEn: "Jiangnan University"
  },
  "jiangsu-university": {
    rank: "81",
    overallRank: 81,
    category: "综合",
    score: 301.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江苏大学",
    nameEn: "Jiangsu University"
  },
  "jiangsu-university-of-science-and-technology": {
    rank: "141",
    overallRank: 141,
    category: "理工",
    score: 224.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江苏科技大学",
    nameEn: "Jiangsu University of Science and Technology"
  },
  "jiangxi-agricultural-university": {
    rank: "207",
    overallRank: 207,
    category: "农业",
    score: 190.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江西农业大学",
    nameEn: "Jiangxi Agricultural University"
  },
  "jiangxi-normal-university": {
    rank: "126",
    overallRank: 126,
    category: "师范",
    score: 238,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江西师范大学",
    nameEn: "Jiangxi Normal University"
  },
  "jiangxi-university-of-finance-and-economics": {
    rank: "财7",
    overallRank: 101,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江西财经大学",
    nameEn: "Jiangxi University of Finance & Economics"
  },
  "jiangxi-university-of-traditional-chinese-medicine": {
    rank: "中医13",
    overallRank: 199,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "江西中医药大学",
    nameEn: "Jiangxi University of Chinese Medicine"
  },
  "jilin-agricultural-university": {
    rank: "161",
    overallRank: 161,
    category: "农业",
    score: 212.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "吉林农业大学",
    nameEn: "Jilin Agricultural University"
  },
  "jilin-normal-university": {
    rank: "322",
    overallRank: 322,
    category: "师范",
    score: 146.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "吉林师范大学",
    nameEn: "Jilin Normal University"
  },
  "jilin-university": {
    rank: "26",
    overallRank: 26,
    category: "综合",
    score: 498.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "吉林大学",
    nameEn: "Jilin University"
  },
  "jinan-university": {
    rank: "59",
    overallRank: 59,
    category: "综合",
    score: 343.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "暨南大学",
    nameEn: "Jinan University"
  },
  "jingdezhen-ceramic-institute": {
    rank: "321",
    overallRank: 321,
    category: "理工",
    score: 146.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "景德镇陶瓷大学",
    nameEn: "Jingdezhen Ceramic University"
  },
  "kunming-medical-university": {
    rank: "医22",
    overallRank: 195,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "昆明医科大学",
    nameEn: "Kunming Medical University"
  },
  "kunming-university-of-science-and-technology": {
    rank: "110",
    overallRank: 110,
    category: "理工",
    score: 260.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "昆明理工大学",
    nameEn: "Kunming University of Science and Technology"
  },
  "lanzhou-jiaotong-university": {
    rank: "192",
    overallRank: 192,
    category: "理工",
    score: 195.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "兰州交通大学",
    nameEn: "Lanzhou Jiaotong University"
  },
  "lanzhou-university": {
    rank: "40",
    overallRank: 40,
    category: "综合",
    score: 388.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "兰州大学",
    nameEn: "Lanzhou University"
  },
  "lanzhou-university-of-technology": {
    rank: "204",
    overallRank: 204,
    category: "理工",
    score: 193,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "兰州理工大学",
    nameEn: "Lanzhou University of Technology"
  },
  "liaoning-medical-university": {
    rank: "医32",
    overallRank: 246,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "锦州医科大学",
    nameEn: "Jinzhou Medical University"
  },
  "liaoning-normal-university": {
    rank: "162",
    overallRank: 162,
    category: "师范",
    score: 211.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁师范大学",
    nameEn: "Liaoning Normal University"
  },
  "liaoning-shihua-university": {
    rank: "263",
    overallRank: 263,
    category: "理工",
    score: 167.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁石油化工大学",
    nameEn: "Liaoning Petrochemical University"
  },
  "liaoning-technical-university": {
    rank: "271",
    overallRank: 271,
    category: "理工",
    score: 164.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁工程技术大学",
    nameEn: "Liaoning Technical University"
  },
  "liaoning-university": {
    rank: "125",
    overallRank: 125,
    category: "综合",
    score: 238.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁大学",
    nameEn: "Liaoning University"
  },
  "liaoning-university-of-technology": {
    rank: "279",
    overallRank: 279,
    category: "理工",
    score: 159.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁工业大学",
    nameEn: "Liaoning University of Technology"
  },
  "liaoning-university-of-traditional-chinese-medicine": {
    rank: "中医12",
    overallRank: 189,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁中医药大学",
    nameEn: "Liaoning University of Traditional Chinese Medicine"
  },
  "ludong-university": {
    rank: "240",
    overallRank: 240,
    category: "综合",
    score: 176.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "鲁东大学",
    nameEn: "Ludong University"
  },
  "lu-xun-academy-of-fine-arts": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "鲁迅美术学院",
    nameEn: "LuXun Academy of Fine Arts",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "minzu-university-of-china": {
    rank: "民1",
    overallRank: 79,
    category: "民族",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中央民族大学",
    nameEn: "Minzu University of China"
  },
  "mudanjiang-normal-university": {
    rank: "468",
    overallRank: 468,
    category: "师范",
    score: 119,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "牡丹江师范学院",
    nameEn: "Mudanjiang Normal University"
  },
  "nanchang-hangkong-university": {
    rank: "181",
    overallRank: 181,
    category: "理工",
    score: 200.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南昌航空大学",
    nameEn: "Nanchang Hangkong University"
  },
  "nanchang-university": {
    rank: "74",
    overallRank: 74,
    category: "综合",
    score: 314.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南昌大学",
    nameEn: "Nanchang University"
  },
  "nanjing-agricultural-university": {
    rank: "55",
    overallRank: 55,
    category: "农业",
    score: 350.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京农业大学",
    nameEn: "Nanjing Agricultural University"
  },
  "nanjing-normal-university": {
    rank: "58",
    overallRank: 58,
    category: "师范",
    score: 344.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京师范大学",
    nameEn: "Nanjing Normal University"
  },
  "nanjing-university": {
    rank: "6",
    overallRank: 6,
    category: "综合",
    score: 708.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京大学",
    nameEn: "Nanjing University"
  },
  "nanjing-university-of-aeronautics-and-astronautics": {
    rank: "37",
    overallRank: 37,
    category: "理工",
    score: 417.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京航空航天大学",
    nameEn: "Nanjing University of Aeronautics and Astronautics"
  },
  "nanjing-university-of-chinese-medicine": {
    rank: "中医3",
    overallRank: 93,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京中医药大学",
    nameEn: "Nanjing University of Chinese Medicine"
  },
  "nanjing-university-of-information-science-and-technology": {
    rank: "98",
    overallRank: 98,
    category: "理工",
    score: 275.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京信息工程大学",
    nameEn: "Nanjing University of Information Science & Technology"
  },
  "nanjing-university-of-science-and-technology": {
    rank: "36",
    overallRank: 36,
    category: "理工",
    score: 419.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南京理工大学",
    nameEn: "Nanjing University of Science & Technology"
  },
  "nanjing-university-of-the-arts": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "南京艺术学院",
    nameEn: "Nanjing University of the Arts",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "nankai-university": {
    rank: "21",
    overallRank: 21,
    category: "综合",
    score: 528.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南开大学",
    nameEn: "Nankai University"
  },
  "ningbo-university": {
    rank: "78",
    overallRank: 78,
    category: "综合",
    score: 310.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "宁波大学",
    nameEn: "Ningbo University"
  },
  "ningbo-university-of-technology": {
    rank: "292",
    overallRank: 292,
    category: "理工",
    score: 155.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "宁波工程学院",
    nameEn: "Ningbo University of Technology"
  },
  "ningxia-medical-university": {
    rank: "医21",
    overallRank: 184,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "宁夏医科大学",
    nameEn: "Ningxia Medical University"
  },
  "ningxia-university": {
    rank: "137",
    overallRank: 137,
    category: "综合",
    score: 230.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "宁夏大学",
    nameEn: "Ningxia University"
  },
  "north-china-electric-power-university": {
    rank: "84",
    overallRank: 84,
    category: "理工",
    score: 293.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华北电力大学",
    nameEn: "North China Electric Power University"
  },
  "northeast-agricultural-university": {
    rank: "120",
    overallRank: 120,
    category: "农业",
    score: 245.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东北农业大学",
    nameEn: "Northeast Agricultural University"
  },
  "northeast-dianli-university": {
    rank: "208",
    overallRank: 208,
    category: "理工",
    score: 189.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东北电力大学",
    nameEn: "Northeast Electric Power University"
  },
  "northeast-forestry-university": {
    rank: "115",
    overallRank: 115,
    category: "林业",
    score: 255.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东北林业大学",
    nameEn: "Northeast Forestry University"
  },
  "northeast-normal-university": {
    rank: "48",
    overallRank: 48,
    category: "师范",
    score: 372.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东北师范大学",
    nameEn: "Northeast Normal University"
  },
  "northeastern-university": {
    rank: "38",
    overallRank: 38,
    category: "理工",
    score: 398.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东北大学",
    nameEn: "Northeastern University"
  },
  "northwest-aandf-university": {
    rank: "69",
    overallRank: 69,
    category: "农业",
    score: 330.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西北农林科技大学",
    nameEn: "Northwest A&F University"
  },
  "northwestern-polytechnical-university": {
    rank: "23",
    overallRank: 23,
    category: "理工",
    score: 519.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西北工业大学",
    nameEn: "Northwestern Polytechnical University"
  },
  "northwest-normal-university": {
    rank: "154",
    overallRank: 154,
    category: "师范",
    score: 216,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西北师范大学",
    nameEn: "Northwest Normal University"
  },
  "northwest-university": {
    rank: "70",
    overallRank: 70,
    category: "综合",
    score: 329.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西北大学",
    nameEn: "Northwest University"
  },
  "ocean-university-of-china": {
    rank: "51",
    overallRank: 51,
    category: "综合",
    score: 359.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国海洋大学",
    nameEn: "Ocean University of China"
  },
  "peking-university": {
    rank: "2",
    overallRank: 2,
    category: "综合",
    score: 1036.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京大学",
    nameEn: "Peking University"
  },
  "qingdao-university": {
    rank: "108",
    overallRank: 108,
    category: "综合",
    score: 263.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "青岛大学",
    nameEn: "Qingdao University"
  },
  "qingdao-university-of-science-and-technology": {
    rank: "167",
    overallRank: 167,
    category: "理工",
    score: 209.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "青岛科技大学",
    nameEn: "Qingdao University of Science & Technology"
  },
  "qinghai-nationalities-university": {
    rank: "民11",
    overallRank: 312,
    category: "民族",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "青海民族大学",
    nameEn: "Qinghai Minzu University"
  },
  "qinghai-university": {
    rank: "203",
    overallRank: 203,
    category: "综合",
    score: 193.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "青海大学",
    nameEn: "Qinghai University"
  },
  "qiqihar-university": {
    rank: "381",
    overallRank: 381,
    category: "综合",
    score: 131.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "齐齐哈尔大学",
    nameEn: "Qiqihar University"
  },
  "renmin-university-of-china": {
    rank: "17",
    overallRank: 17,
    category: "综合",
    score: 558.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国人民大学",
    nameEn: "Renmin University of China"
  },
  "shaanxi-normal-university": {
    rank: "63",
    overallRank: 63,
    category: "师范",
    score: 342,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "陕西师范大学",
    nameEn: "Shaanxi Normal University"
  },
  "shaanxi-university-of-chinese-medicine": {
    rank: "中医18",
    overallRank: 239,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "陕西中医药大学",
    nameEn: "Shaanxi University of Chinese Medicine"
  },
  "shandong-normal-university": {
    rank: "104",
    overallRank: 104,
    category: "师范",
    score: 268.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "山东师范大学",
    nameEn: "Shandong Normal University"
  },
  "shandong-university": {
    rank: "22",
    overallRank: 22,
    category: "综合",
    score: 527.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "山东大学",
    nameEn: "Shandong University"
  },
  "shandong-university-of-science-and-technology": {
    rank: "140",
    overallRank: 140,
    category: "理工",
    score: 226.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "山东科技大学",
    nameEn: "Shandong University of Science and Technology"
  },
  "shandong-university-of-technology": {
    rank: "197",
    overallRank: 197,
    category: "理工",
    score: 194.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "山东理工大学",
    nameEn: "Shandong University of Technology"
  },
  "shanghai-conservatory-of-music": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "上海音乐学院",
    nameEn: "Shanghai Conservatory of Music",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "shanghai-international-studies-university": {
    rank: "语2",
    overallRank: 81,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海外国语大学",
    nameEn: "Shanghai International Studies University"
  },
  "shanghai-jiao-tong-university": {
    rank: "4",
    overallRank: 4,
    category: "综合",
    score: 894.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海交通大学",
    nameEn: "Shanghai Jiao Tong University"
  },
  "shanghai-maritime-university": {
    rank: "171",
    overallRank: 171,
    category: "综合",
    score: 207.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海海事大学",
    nameEn: "Shanghai Maritime University"
  },
  "shanghai-normal-university": {
    rank: "123",
    overallRank: 123,
    category: "师范",
    score: 238.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海师范大学",
    nameEn: "Shanghai Normal University"
  },
  "shanghai-ocean-university": {
    rank: "142",
    overallRank: 142,
    category: "农业",
    score: 222.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海海洋大学",
    nameEn: "Shanghai Ocean University"
  },
  "shanghai-university": {
    rank: "60",
    overallRank: 60,
    category: "综合",
    score: 343.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海大学",
    nameEn: "Shanghai University"
  },
  "shanghai-university-of-finance-and-economics": {
    rank: "财1",
    overallRank: 35,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海财经大学",
    nameEn: "Shanghai University of Finance and Economics"
  },
  "shanghai-university-of-international-business-and-economics": {
    rank: "财14",
    overallRank: 143,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海对外经贸大学",
    nameEn: "Shanghai University of International Business and Economics"
  },
  "shanghai-university-of-political-science-and-law": {
    rank: "政6",
    overallRank: 216,
    category: "政法",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海政法学院",
    nameEn: "Shanghai University of Political Science and Law"
  },
  "shanghai-university-of-sport": {
    rank: "体1",
    overallRank: 131,
    category: "体育",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海体育大学",
    nameEn: "Shanghai University of Sport"
  },
  "shanghai-university-of-traditional-chinese-medicine": {
    rank: "中医2",
    overallRank: 69,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海中医药大学",
    nameEn: "Shanghai University of Traditional Chinese Medicine"
  },
  "shantou-university": {
    rank: "173",
    overallRank: 173,
    category: "综合",
    score: 206.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "汕头大学",
    nameEn: "Shantou University"
  },
  "shanxi-university": {
    rank: "102",
    overallRank: 102,
    category: "综合",
    score: 272.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "山西大学",
    nameEn: "Shanxi University"
  },
  "shenyang-aerospace-university": {
    rank: "179",
    overallRank: 179,
    category: "理工",
    score: 202.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "沈阳航空航天大学",
    nameEn: "Shenyang Aerospace University"
  },
  "shenyang-jianzhu-university": {
    rank: "222",
    overallRank: 222,
    category: "理工",
    score: 182.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "沈阳建筑大学",
    nameEn: "Shenyang Jianzhu University"
  },
  "shenyang-ligong-university": {
    rank: "254",
    overallRank: 254,
    category: "理工",
    score: 170.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "沈阳理工大学",
    nameEn: "Shenyang Ligong University"
  },
  "shenyang-normal-university": {
    rank: "277",
    overallRank: 277,
    category: "师范",
    score: 162,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "沈阳师范大学",
    nameEn: "Shenyang Normal University"
  },
  "shenyang-university-of-technology": {
    rank: "198",
    overallRank: 198,
    category: "理工",
    score: 194.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "沈阳工业大学",
    nameEn: "Shenyang University of Technology"
  },
  "shihezi-university": {
    rank: "135",
    overallRank: 135,
    category: "综合",
    score: 231.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "石河子大学",
    nameEn: "Shihezi University"
  },
  "shenzhen-university": {
    rank: "66",
    overallRank: 66,
    category: "综合",
    score: 341.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "深圳大学",
    nameEn: "Shenzhen University"
  },
  "sichuan-international-studies-university": {
    rank: "语10",
    overallRank: 241,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "四川外国语大学",
    nameEn: "Sichuan International Studies University"
  },
  "sichuan-university": {
    rank: "16",
    overallRank: 16,
    category: "综合",
    score: 581.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "四川大学",
    nameEn: "Sichuan University"
  },
  "soochow-university": {
    rank: "46",
    overallRank: 46,
    category: "综合",
    score: 374.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "苏州大学",
    nameEn: "Soochow University"
  },
  "south-china-agricultural-university": {
    rank: "103",
    overallRank: 103,
    category: "农业",
    score: 270.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华南农业大学",
    nameEn: "South China Agricultural University"
  },
  "south-china-normal-university": {
    rank: "79",
    overallRank: 79,
    category: "师范",
    score: 306.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华南师范大学",
    nameEn: "South China Normal University"
  },
  "south-china-university-of-technology": {
    rank: "32",
    overallRank: 32,
    category: "理工",
    score: 456.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "华南理工大学",
    nameEn: "South China University of Technology"
  },
  "southeast-university": {
    rank: "15",
    overallRank: 15,
    category: "综合",
    score: 592.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "东南大学",
    nameEn: "Southeast University"
  },
  "southern-medical-university": {
    rank: "医3",
    overallRank: 42,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "南方医科大学",
    nameEn: "Southern Medical University"
  },
  "southwest-jiaotong-university": {
    rank: "49",
    overallRank: 49,
    category: "理工",
    score: 366.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西南交通大学",
    nameEn: "Southwest Jiaotong University"
  },
  "southwest-university": {
    rank: "61",
    overallRank: 61,
    category: "综合",
    score: 343,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西南大学",
    nameEn: "Southwest University"
  },
  "southwest-university-of-political-science-and-law": {
    rank: "政3",
    overallRank: 124,
    category: "政法",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西南政法大学",
    nameEn: "Southwest University of Political Science & Law"
  },
  "southwest-university-of-finance-and-economics": {
    rank: "财5",
    overallRank: 66,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西南财经大学",
    nameEn: "Southwestern University of Finance and Economics"
  },
  "southwestern-university-of-finance-and-economics": {
    rank: "财5",
    overallRank: 66,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西南财经大学",
    nameEn: "Southwestern University of Finance and Economics"
  },
  "sun-yat-sen-university": {
    rank: "13",
    overallRank: 13,
    category: "综合",
    score: 597.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中山大学",
    nameEn: "Sun Yat-sen University"
  },
  "taiyuan-university-of-technology": {
    rank: "97",
    overallRank: 97,
    category: "理工",
    score: 275.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "太原理工大学",
    nameEn: "Taiyuan University of Technology"
  },
  "the-central-academy-of-drama": {
    rank: "艺术类高校名单",
    category: "艺术",
    source: "软科2026中国艺术类高校名单",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202630",
    year: 2026,
    nameCn: "中央戏剧学院",
    nameEn: "The Central Academy of Drama",
    note: "软科艺术类高校名单按学校名称展示，不提供序位。"
  },
  "the-graduate-school-of-the-chinese-academy-of-agricultural-sciences": {
    rank: "未列入软科2026榜单",
    category: "未列入",
    source: "软科2026中国大学排名及分类榜检索",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "The Graduate School of the Chinese Academy of Agricultural Sciences",
    nameEn: "The Graduate School of the Chinese Academy of Agricultural Sciences",
    note: "研究生院/科研院所属性较强，未在软科2026中国大学排名/分类榜中检索到该校记录。"
  },
  "tianjin-foreign-studies-university": {
    rank: "语11",
    overallRank: 258,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津外国语大学",
    nameEn: "Tianjin Foreign Studies University"
  },
  "tianjin-medical-university": {
    rank: "医5",
    overallRank: 60,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津医科大学",
    nameEn: "Tianjin Medical University"
  },
  "tianjin-polytechnic-university": {
    rank: "133",
    overallRank: 133,
    category: "理工",
    score: 231.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津工业大学",
    nameEn: "Tiangong University"
  },
  "tianjin-university": {
    rank: "20",
    overallRank: 20,
    category: "理工",
    score: 544.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津大学",
    nameEn: "Tianjin University"
  },
  "tianjin-university-of-finance-and-economics": {
    rank: "财16",
    overallRank: 175,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津财经大学",
    nameEn: "Tianjin University of Finance and Economics"
  },
  "tianjin-university-of-science-and-technology": {
    rank: "158",
    overallRank: 158,
    category: "理工",
    score: 214.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津科技大学",
    nameEn: "Tianjin University of Science and Technology"
  },
  "tianjin-university-of-technology": {
    rank: "170",
    overallRank: 170,
    category: "理工",
    score: 208.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津理工大学",
    nameEn: "Tianjin University of Technology"
  },
  "tianjin-university-of-technology-and-education": {
    rank: "343",
    overallRank: 343,
    category: "师范",
    score: 140.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津职业技术师范大学",
    nameEn: "TianJin University of Technology and Education"
  },
  "tianjin-university-of-traditional-chinese-medicine": {
    rank: "中医5",
    overallRank: 120,
    category: "中医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津中医药大学",
    nameEn: "Tianjin University of Traditional Chinese Medicine"
  },
  "tianjin-normal-university": {
    rank: "160",
    overallRank: 160,
    category: "师范",
    score: 213.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "天津师范大学",
    nameEn: "Tianjin Normal University"
  },
  "tongji-university": {
    rank: "18",
    overallRank: 18,
    category: "综合",
    score: 556.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "同济大学",
    nameEn: "Tongji University"
  },
  "tsinghua-university": {
    rank: "1",
    overallRank: 1,
    category: "综合",
    score: 1087.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "清华大学",
    nameEn: "Tsinghua University"
  },
  "university-of-chinese-academy-of-sciences": {
    rank: "未列入软科2026榜单",
    category: "未列入",
    source: "软科2026中国大学排名及分类榜检索",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "University of Chinese Academy of Sciences",
    nameEn: "University of Chinese Academy of Sciences",
    note: "科研院所型高校，未在软科2026中国大学排名/分类榜中检索到该校记录。"
  },
  "university-of-electronic-science-and-technology-of-china": {
    rank: "33",
    overallRank: 33,
    category: "理工",
    score: 453.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "电子科技大学",
    nameEn: "University of Electronic Science and Technology of China"
  },
  "university-of-international-business-and-economics": {
    rank: "财3",
    overallRank: 57,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "对外经济贸易大学",
    nameEn: "University of International Business and Economics"
  },
  "university-of-jinan": {
    rank: "175",
    overallRank: 175,
    category: "综合",
    score: 205,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "济南大学",
    nameEn: "University of Jinan"
  },
  "university-of-science-and-technology-of-china": {
    rank: "7",
    overallRank: 7,
    category: "理工",
    score: 653.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中国科学技术大学",
    nameEn: "University of Science and Technology of China"
  },
  "university-of-science-and-technology-beijing": {
    rank: "35",
    overallRank: 35,
    category: "理工",
    score: 429.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "北京科技大学",
    nameEn: "University of Science and Technology Beijing"
  },
  "university-of-science-and-technology-liaoning": {
    rank: "304",
    overallRank: 304,
    category: "理工",
    score: 152,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "辽宁科技大学",
    nameEn: "University of Science and Technology Liaoning"
  },
  "university-of-shanghai-for-science-and-technology": {
    rank: "106",
    overallRank: 106,
    category: "理工",
    score: 266.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "上海理工大学",
    nameEn: "University of Shanghai for Science and Technology"
  },
  "wenzhou-medical-university": {
    rank: "医11",
    overallRank: 91,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "温州医科大学",
    nameEn: "Wenzhou Medical University"
  },
  "wenzhou-kean-university": {
    rank: "合作8",
    overallRank: 151,
    category: "综合",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "温州肯恩大学",
    nameEn: "Wenzhou-Kean University"
  },
  "wenzhou-university": {
    rank: "129",
    overallRank: 129,
    category: "综合",
    score: 234.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "温州大学",
    nameEn: "Wenzhou University"
  },
  "wuhan-institute-of-physical-education": {
    rank: "体4",
    overallRank: 282,
    category: "体育",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "武汉体育学院",
    nameEn: "Wuhan Sports University"
  },
  "wuhan-textile-university": {
    rank: "159",
    overallRank: 159,
    category: "理工",
    score: 214,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "武汉纺织大学",
    nameEn: "Wuhan Textile University"
  },
  "wuhan-university": {
    rank: "8",
    overallRank: 8,
    category: "综合",
    score: 638.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "武汉大学",
    nameEn: "Wuhan University"
  },
  "wuhan-university-of-technology": {
    rank: "54",
    overallRank: 54,
    category: "理工",
    score: 351.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "武汉理工大学",
    nameEn: "Wuhan University of Technology"
  },
  "wuyi-university": {
    rank: "311",
    overallRank: 311,
    category: "综合",
    score: 149.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "五邑大学",
    nameEn: "Wuyi University"
  },
  "xiamen-university": {
    rank: "25",
    overallRank: 25,
    category: "综合",
    score: 512.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "厦门大学",
    nameEn: "Xiamen University"
  },
  "xiamen-university-of-technology": {
    rank: "246",
    overallRank: 246,
    category: "理工",
    score: 172.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "厦门理工学院",
    nameEn: "Xiamen University of Technology"
  },
  "xi-an-international-studies-university": {
    rank: "语9",
    overallRank: 241,
    category: "语言",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西安外国语大学",
    nameEn: "Xi'an International Studies University"
  },
  "xi-an-jiaotong-university": {
    rank: "10",
    overallRank: 10,
    category: "综合",
    score: 620.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西安交通大学",
    nameEn: "Xi'an Jiaotong University"
  },
  "xi-an-shiyou-university": {
    rank: "230",
    overallRank: 230,
    category: "理工",
    score: 179.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西安石油大学",
    nameEn: "Xi'an Shiyou University"
  },
  "xiangtan-university": {
    rank: "117",
    overallRank: 117,
    category: "综合",
    score: 253.7,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "湘潭大学",
    nameEn: "Xiangtan University"
  },
  "xidian-university": {
    rank: "39",
    overallRank: 39,
    category: "理工",
    score: 391.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "西安电子科技大学",
    nameEn: "Xidian University"
  },
  "xinjiang-medical-university": {
    rank: "医23",
    overallRank: 196,
    category: "医药",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "新疆医科大学",
    nameEn: "Xinjiang Medical University"
  },
  "xinjiang-normal-university": {
    rank: "302",
    overallRank: 302,
    category: "师范",
    score: 152.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "新疆师范大学",
    nameEn: "Xinjiang Normal University"
  },
  "xinjiang-university": {
    rank: "131",
    overallRank: 131,
    category: "综合",
    score: 233.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "新疆大学",
    nameEn: "Xinjiang University"
  },
  "yanbian-university": {
    rank: "157",
    overallRank: 157,
    category: "综合",
    score: 214.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "延边大学",
    nameEn: "Yanbian University"
  },
  "yangtze-university": {
    rank: "184",
    overallRank: 184,
    category: "综合",
    score: 199.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "长江大学",
    nameEn: "Yangtze University"
  },
  "yangzhou-university": {
    rank: "93",
    overallRank: 93,
    category: "综合",
    score: 280.3,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "扬州大学",
    nameEn: "Yangzhou University"
  },
  "yanshan-university": {
    rank: "109",
    overallRank: 109,
    category: "理工",
    score: 261.9,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "燕山大学",
    nameEn: "Yanshan University"
  },
  "yantai-university": {
    rank: "224",
    overallRank: 224,
    category: "综合",
    score: 181.5,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "烟台大学",
    nameEn: "Yantai University"
  },
  "yunnan-agricultural-university": {
    rank: "290",
    overallRank: 290,
    category: "农业",
    score: 156,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "云南农业大学",
    nameEn: "Yunnan Agricultural University"
  },
  "yunnan-normal-university": {
    rank: "198",
    overallRank: 198,
    category: "师范",
    score: 194.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "云南师范大学",
    nameEn: "Yunnan Normal University"
  },
  "yunnan-university": {
    rank: "71",
    overallRank: 71,
    category: "综合",
    score: 325.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "云南大学",
    nameEn: "Yunnan University"
  },
  "yunnan-university-of-finance-and-economics": {
    rank: "财31",
    overallRank: 281,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "云南财经大学",
    nameEn: "Yunnan University of Finance and Economics"
  },
  "yunnan-university-of-nationalities": {
    rank: "民10",
    overallRank: 299,
    category: "民族",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "云南民族大学",
    nameEn: "Yunnan Minzu University"
  },
  "zhejiang-gongshang-university": {
    rank: "财8",
    overallRank: 101,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江工商大学",
    nameEn: "Zhejiang Gongshang University"
  },
  "zhejiang-normal-university": {
    rank: "91",
    overallRank: 91,
    category: "师范",
    score: 282.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江师范大学",
    nameEn: "Zhejiang Normal University"
  },
  "zhejiang-ocean-university": {
    rank: "236",
    overallRank: 236,
    category: "农业",
    score: 178.1,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江海洋大学",
    nameEn: "Zhejiang Ocean University"
  },
  "zhejiang-sci-tech-university": {
    rank: "112",
    overallRank: 112,
    category: "理工",
    score: 259.2,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江理工大学",
    nameEn: "Zhejiang Sci-Tech University"
  },
  "zhejiang-university": {
    rank: "3",
    overallRank: 3,
    category: "综合",
    score: 895.6,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江大学",
    nameEn: "Zhejiang University"
  },
  "zhejiang-university-of-science-and-technology": {
    rank: "232",
    overallRank: 232,
    category: "理工",
    score: 178.8,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江科技大学",
    nameEn: "Zhejiang University of Science & Technology"
  },
  "zhejiang-university-of-technology": {
    rank: "68",
    overallRank: 68,
    category: "理工",
    score: 334.4,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "浙江工业大学",
    nameEn: "Zhejiang University of Technology"
  },
  "zhengzhou-university": {
    rank: "44",
    overallRank: 44,
    category: "综合",
    score: 380,
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "郑州大学",
    nameEn: "Zhengzhou University"
  },
  "zhongnan-university-of-economics-and-law": {
    rank: "财4",
    overallRank: 57,
    category: "财经",
    source: "软科2026中国大学排名（总榜）",
    sourceUrl: "https://www.shanghairanking.cn/rankings/bcur/202610",
    year: 2026,
    nameCn: "中南财经政法大学",
    nameEn: "Zhongnan University of Economics and Law"
  }
};

export function getChinaUniversityRanking(slug: string) {
  return chinaUniversityRankings[slug];
}

export function getChinaRankingSortValue(university: { chinaRanking?: ChinaUniversityRanking }) {
  const ranking = university.chinaRanking;
  if (!ranking) return Number.POSITIVE_INFINITY;
  if (ranking.overallRank) return ranking.overallRank;
  const numeric = ranking.rank.match(/\d+/)?.[0];
  return numeric ? Number(numeric) : Number.POSITIVE_INFINITY;
}
